// ---------------------------------------------------------------------------
// NICU clinical catalogue
// Content aligned with AAP (Levels of Neonatal Care / NRP / Bilirubin & ROP
// guidance), NNF India Clinical Practice Guidelines and IAP recommendations.
// Everything here is tap-selectable so nurses / residents type almost nothing.
// ---------------------------------------------------------------------------

export type SystemKey =
  | "Respiratory"
  | "Cardiovascular"
  | "Neurology"
  | "Gastro / Nutrition"
  | "Metabolic / Endocrine"
  | "Infection"
  | "Haematology / Bilirubin"
  | "Renal / GU"
  | "Thermoregulation"
  | "Eye / ENT"
  | "Surgical"
  | "Genetic / Syndromic"
  | "Birth injury / Skin"
  | "Growth / Prematurity";

export const SYSTEMS: SystemKey[] = [
  "Respiratory",
  "Cardiovascular",
  "Neurology",
  "Gastro / Nutrition",
  "Metabolic / Endocrine",
  "Infection",
  "Haematology / Bilirubin",
  "Renal / GU",
  "Thermoregulation",
  "Eye / ENT",
  "Surgical",
  "Genetic / Syndromic",
  "Birth injury / Skin",
  "Growth / Prematurity",
];

export const PROBLEM_CATALOG: Record<SystemKey, string[]> = {
  Respiratory: [
    "Respiratory distress syndrome (HMD) Gr I",
    "RDS Gr II",
    "RDS Gr III",
    "RDS Gr IV",
    "Transient tachypnoea of newborn (TTNB)",
    "Meconium aspiration syndrome",
    "Congenital pneumonia",
    "Ventilator associated pneumonia",
    "Apnoea of prematurity",
    "Obstructive apnoea / desaturation spells",
    "Pneumothorax",
    "Pneumomediastinum / air leak",
    "Pulmonary interstitial emphysema",
    "Pulmonary haemorrhage",
    "PPHN",
    "Bronchopulmonary dysplasia / CLD",
    "Atelectasis / lung collapse",
    "Pleural effusion / chylothorax",
    "Congenital diaphragmatic hernia",
    "Congenital lobar emphysema / CCAM",
    "Tracheo-oesophageal fistula with aspiration",
    "Choanal atresia",
    "Laryngomalacia / stridor",
    "Post-extubation stridor",
    "Subglottic stenosis",
    "Failed extubation",
    "Difficult airway",
    "Respiratory acidosis",
    "Surfactant deficiency – repeat dose given",
  ],
  Cardiovascular: [
    "Haemodynamically significant PDA",
    "Silent PDA (echo)",
    "Neonatal shock – hypovolaemic",
    "Septic shock",
    "Cardiogenic shock / myocardial dysfunction",
    "Refractory hypotension (on inotropes)",
    "Persistent pulmonary hypertension",
    "Cyanotic CHD – TGA",
    "Cyanotic CHD – TOF",
    "Cyanotic CHD – TAPVC",
    "Cyanotic CHD – Tricuspid atresia",
    "Cyanotic CHD – Truncus arteriosus",
    "Acyanotic CHD – VSD",
    "Acyanotic CHD – ASD",
    "Acyanotic CHD – AV canal defect",
    "Coarctation of aorta / interrupted arch",
    "Hypoplastic left heart syndrome",
    "Critical pulmonary / aortic stenosis",
    "Duct dependent circulation – on PGE1",
    "Supraventricular tachycardia",
    "Bradyarrhythmia / congenital heart block",
    "Pericardial effusion / tamponade",
    "Cardiomyopathy (IDM / metabolic)",
    "Systemic hypertension",
  ],
  Neurology: [
    "Perinatal asphyxia",
    "HIE Stage I (Sarnat)",
    "HIE Stage II (Sarnat)",
    "HIE Stage III (Sarnat)",
    "Therapeutic hypothermia – ongoing",
    "Therapeutic hypothermia – rewarming",
    "Neonatal seizures – clinical",
    "Neonatal seizures – electrographic (aEEG/EEG)",
    "Status epilepticus",
    "IVH Grade I",
    "IVH Grade II",
    "IVH Grade III",
    "IVH Grade IV / PVHI",
    "Post-haemorrhagic ventricular dilatation",
    "Periventricular leukomalacia",
    "Neonatal stroke / infarct",
    "Meningitis",
    "Congenital hydrocephalus",
    "Neural tube defect – meningomyelocele",
    "Encephalopathy of unclear cause",
    "Hypotonia / floppy infant",
    "Bilirubin induced neurological dysfunction",
    "Neonatal abstinence syndrome",
    "Abnormal cranial ultrasound – for follow up",
    "Microcephaly / macrocephaly",
  ],
  "Gastro / Nutrition": [
    "Feed intolerance",
    "Large gastric residuals",
    "Abdominal distension – under observation",
    "NEC Bell Stage I (suspect)",
    "NEC Bell Stage IIA/IIB",
    "NEC Bell Stage IIIA/IIIB",
    "Spontaneous intestinal perforation",
    "Post NEC stricture",
    "Gastro-oesophageal reflux",
    "Delayed passage of meconium",
    "Neonatal cholestasis",
    "Conjugated hyperbilirubinaemia / TPN cholestasis",
    "Hepatomegaly – for evaluation",
    "Oesophageal atresia with TEF",
    "Gastroschisis",
    "Omphalocele",
    "Malrotation / volvulus",
    "Hirschsprung disease – suspected",
    "Anorectal malformation",
    "Duodenal / jejunal atresia",
    "Inguinal hernia",
    "Short bowel syndrome / on TPN",
    "Extrauterine growth restriction (EUGR)",
    "Slow weight gain (<15 g/kg/day)",
    "Oral feeding immaturity / poor suck",
  ],
  "Metabolic / Endocrine": [
    "Hypoglycaemia – asymptomatic",
    "Hypoglycaemia – symptomatic",
    "Recurrent / refractory hypoglycaemia (GIR >8)",
    "Hyperinsulinism",
    "Hyperglycaemia – on insulin",
    "Early hypocalcaemia",
    "Late hypocalcaemia",
    "Hypomagnesaemia",
    "Hyponatraemia",
    "Hypernatraemia / dehydration",
    "Hypokalaemia",
    "Hyperkalaemia",
    "Metabolic acidosis",
    "Metabolic alkalosis",
    "Lactic acidosis",
    "Inborn error of metabolism – suspected",
    "Congenital hypothyroidism",
    "Congenital adrenal hyperplasia",
    "Infant of diabetic mother",
    "Metabolic bone disease of prematurity",
    "Hyperammonaemia",
  ],
  Infection: [
    "Risk factors for early onset sepsis – on watch",
    "Clinical early onset sepsis",
    "Culture positive EOS",
    "Clinical late onset sepsis",
    "Culture positive LOS",
    "Blood culture: Klebsiella",
    "Blood culture: Acinetobacter",
    "Blood culture: E. coli",
    "Blood culture: CoNS",
    "Blood culture: Staph aureus / MRSA",
    "Blood culture: Group B Streptococcus",
    "Blood culture: Enterococcus",
    "Blood culture: Candida",
    "Multi-drug resistant organism – contact isolation",
    "CLABSI",
    "Meningitis – CSF proven",
    "Urinary tract infection",
    "Omphalitis",
    "Neonatal conjunctivitis",
    "Skin pustulosis / abscess",
    "Fungal sepsis – on antifungal",
    "Congenital infection – CMV",
    "Congenital infection – Toxoplasma",
    "Congenital infection – Rubella",
    "Congenital infection – Syphilis",
    "Perinatal HIV exposure – on prophylaxis",
    "Hepatitis B exposed – Ig + vaccine given",
    "Maternal COVID / respiratory infection exposure",
    "Neonatal tetanus",
  ],
  "Haematology / Bilirubin": [
    "Physiological jaundice",
    "Non-haemolytic hyperbilirubinaemia – phototherapy",
    "Rh isoimmunisation",
    "ABO incompatibility",
    "G6PD deficiency",
    "Hereditary spherocytosis – suspected",
    "Exchange transfusion threshold – prepared",
    "Post exchange transfusion",
    "Prolonged jaundice (>14 days)",
    "Anaemia of prematurity",
    "Anaemia – needs PRBC transfusion",
    "Polycythaemia",
    "Partial exchange done",
    "Thrombocytopenia – mild (100–150k)",
    "Thrombocytopenia – severe (<50k)",
    "Neonatal alloimmune thrombocytopenia",
    "Disseminated intravascular coagulation",
    "Vitamin K deficiency bleeding",
    "Neutropenia",
    "Thrombosis – line associated",
    "Subgaleal haemorrhage",
  ],
  "Renal / GU": [
    "Acute kidney injury",
    "Oliguria (<1 ml/kg/hr)",
    "Antenatal hydronephrosis",
    "Posterior urethral valves",
    "Multicystic dysplastic kidney",
    "Renal agenesis",
    "Renal vein thrombosis",
    "Urinary tract infection",
    "Ambiguous genitalia",
    "Undescended testis",
    "Hypospadias",
    "Hydrocele",
    "Bladder exstrophy",
  ],
  Thermoregulation: [
    "Hypothermia on admission (cold stress)",
    "Recurrent hypothermia",
    "Hyperthermia / environmental",
    "Unstable temperature – for sepsis screen",
    "Weaning from incubator to cot",
  ],
  "Eye / ENT": [
    "ROP screening due",
    "ROP screening – immature retina",
    "ROP Stage 1",
    "ROP Stage 2",
    "ROP Stage 3",
    "Aggressive posterior ROP",
    "Plus disease – treatment needed",
    "Post anti-VEGF / laser therapy",
    "Congenital cataract",
    "Nasolacrimal duct obstruction",
    "Hearing screen (OAE) refer",
    "BERA abnormal – audiology follow up",
    "Cleft lip / palate",
    "Pierre Robin sequence",
  ],
  Surgical: [
    "Pre-operative – NPO, consent taken",
    "Post-operative day 1",
    "Post-operative – on ventilator",
    "Stoma care / high stoma output",
    "Surgical site infection",
    "Chest drain in situ",
    "Peritoneal drain in situ",
    "Awaiting surgical opinion",
    "Awaiting cardiac surgery / cath",
  ],
  "Genetic / Syndromic": [
    "Down syndrome (Trisomy 21)",
    "Edwards syndrome (Trisomy 18)",
    "Patau syndrome (Trisomy 13)",
    "Turner syndrome",
    "VACTERL association",
    "CHARGE association",
    "Skeletal dysplasia / achondroplasia",
    "Dysmorphic – karyotype / microarray sent",
    "Consanguineous parents – genetic counselling",
    "Multiple congenital anomalies",
  ],
  "Birth injury / Skin": [
    "Caput succedaneum",
    "Cephalhaematoma",
    "Subgaleal bleed",
    "Clavicle fracture",
    "Erb's palsy / brachial plexus injury",
    "Facial nerve palsy",
    "Scalp electrode / instrumental injury",
    "Extravasation injury",
    "Pressure injury (CPAP prongs / probe)",
    "Diaper dermatitis",
    "Sclerema",
    "Vesiculobullous rash – for evaluation",
    "Haemangioma / vascular malformation",
  ],
  "Growth / Prematurity": [
    "Extremely low birth weight (<1000 g)",
    "Very low birth weight (1000–1499 g)",
    "Low birth weight (1500–2499 g)",
    "Extreme preterm (<28 weeks)",
    "Very preterm (28–31+6 weeks)",
    "Moderate preterm (32–33+6 weeks)",
    "Late preterm (34–36+6 weeks)",
    "Small for gestational age / IUGR",
    "Large for gestational age",
    "Post-term",
    "Antenatal steroids – complete course",
    "Antenatal steroids – incomplete / none",
    "Delayed cord clamping done",
    "Twin / multiple gestation",
  ],
};

export const RESP_MODES = [
  "Room air",
  "O2 by hood",
  "Nasal prongs O2",
  "HFNC",
  "Bubble CPAP",
  "Ventilator CPAP",
  "NIPPV / NIV-NAVA",
  "SIMV + PS",
  "AC / PRVC",
  "Volume guarantee",
  "HFOV",
  "HFJV",
  "iNO therapy",
  "T-piece / bagging",
  "Self inflating bag standby",
];

export const RESP_FIELDS = [
  { key: "fio2", label: "FiO₂ %", min: 21, max: 100, step: 5, def: 21 },
  { key: "peep", label: "PEEP/CPAP", min: 0, max: 12, step: 1, def: 5 },
  { key: "pip", label: "PIP", min: 0, max: 35, step: 1, def: 16 },
  { key: "rate", label: "Rate", min: 0, max: 80, step: 5, def: 40 },
  { key: "ti", label: "Ti (s)", min: 0.2, max: 0.6, step: 0.05, def: 0.35 },
  { key: "map", label: "MAP cmH₂O", min: 4, max: 20, step: 1, def: 8 },
  { key: "amplitude", label: "ΔP (HFOV)", min: 0, max: 60, step: 2, def: 20 },
  { key: "hz", label: "Hz", min: 5, max: 15, step: 1, def: 10 },
  { key: "flow", label: "Flow L/min", min: 0, max: 12, step: 0.5, def: 6 },
  { key: "ino", label: "iNO ppm", min: 0, max: 20, step: 5, def: 0 },
] as const;

export const SURFACTANT = [
  "Not given",
  "Prophylactic – 1 dose",
  "Rescue – 1 dose",
  "2nd dose given",
  "3rd dose given",
  "INSURE",
  "LISA / MIST",
];

export const FEED_TYPE = [
  "NPO / Nil per oral",
  "Trophic feeds",
  "Expressed breast milk (EBM)",
  "Direct breastfeeding",
  "Donor human milk",
  "EBM + HMF",
  "Preterm formula",
  "Term formula",
  "Lactose free / hydrolysed formula",
  "Post-discharge formula",
];

export const FEED_ROUTE = [
  "Breast",
  "Paladai",
  "Katori-spoon",
  "Cup",
  "Bottle",
  "OG tube",
  "NG tube",
  "Gavage bolus",
  "Continuous infusion",
  "Gastrostomy",
];

export const LINES = [
  "Peripheral IV cannula",
  "Umbilical venous catheter",
  "Umbilical arterial catheter",
  "PICC line",
  "Central venous line",
  "Arterial line",
  "Endotracheal tube",
  "Tracheostomy",
  "CPAP prongs / mask",
  "OG tube",
  "NG tube",
  "Foley catheter",
  "Intercostal drain",
  "Peritoneal drain",
  "Stoma bag",
  "aEEG leads",
  "Cooling mattress",
];

export const DRUGS: Record<string, string[]> = {
  Antibiotics: [
    "Ampicillin",
    "Penicillin G",
    "Amoxicillin-Clavulanate",
    "Cefotaxime",
    "Ceftazidime",
    "Ceftriaxone",
    "Piperacillin-tazobactam",
    "Amikacin",
    "Gentamicin",
    "Netilmicin",
    "Meropenem",
    "Vancomycin",
    "Teicoplanin",
    "Colistin",
    "Clindamycin",
    "Metronidazole",
    "Linezolid",
    "Cloxacillin",
  ],
  Antifungal: ["Fluconazole", "Amphotericin B (LAmB)", "Micafungin", "Nystatin oral"],
  Antiviral: ["Acyclovir", "Ganciclovir / Valganciclovir", "Zidovudine prophylaxis"],
  Cardiac: [
    "Dopamine",
    "Dobutamine",
    "Adrenaline",
    "Noradrenaline",
    "Milrinone",
    "Vasopressin",
    "Hydrocortisone (for hypotension)",
    "PGE1 infusion",
    "Adenosine",
    "Digoxin",
    "Propranolol",
    "Sildenafil",
    "Bosentan",
  ],
  Respiratory: [
    "Caffeine citrate",
    "Aminophylline",
    "Surfactant",
    "Nebulised adrenaline",
    "Budesonide neb",
    "Dexamethasone (DART)",
    "Furosemide (for CLD)",
  ],
  Neuro: [
    "Phenobarbitone",
    "Levetiracetam",
    "Fosphenytoin",
    "Midazolam infusion",
    "Lignocaine infusion",
    "Pyridoxine trial",
    "Fentanyl",
    "Morphine",
    "Dexmedetomidine",
    "Paracetamol (analgesia)",
    "Sucrose 24% for procedures",
  ],
  "PDA / Fluids": [
    "Paracetamol IV (PDA)",
    "Ibuprofen (PDA)",
    "Indomethacin (PDA)",
    "Furosemide",
    "Spironolactone",
    "Chlorothiazide",
    "Normal saline bolus",
    "Sodium bicarbonate",
    "Calcium gluconate",
    "Insulin infusion",
    "Dextrose 10% bolus",
  ],
  Supplements: [
    "Vitamin K",
    "Multivitamin drops",
    "Vitamin D3 400 IU",
    "Iron 2–4 mg/kg/day",
    "Calcium + phosphate",
    "Zinc",
    "Probiotics",
    "Folic acid",
    "Erythropoietin",
    "Levothyroxine",
    "Ursodeoxycholic acid",
    "IVIG",
  ],
};

export const LAB_PANELS: { key: string; label: string; fields: string[] }[] = [
  {
    key: "cbc",
    label: "CBC",
    fields: ["Hb", "Hct", "TLC", "ANC", "Platelets", "nRBC", "I:T ratio"],
  },
  { key: "sepsis", label: "Sepsis screen", fields: ["CRP", "Procalcitonin", "Micro-ESR", "Blood culture"] },
  {
    key: "abg",
    label: "ABG",
    fields: ["pH", "pCO2", "pO2", "HCO3", "BE", "Lactate", "SaO2"],
  },
  {
    key: "biochem",
    label: "Biochemistry",
    fields: ["Na", "K", "Cl", "Ca (ionised)", "Mg", "PO4", "ALP", "Urea", "Creatinine", "Albumin"],
  },
  {
    key: "bili",
    label: "Bilirubin",
    fields: ["TSB", "Direct", "TcB", "DCT", "Blood group", "Retic"],
  },
  { key: "sugar", label: "Glucose", fields: ["RBS / GRBS", "Lab glucose", "GIR"] },
  { key: "liver", label: "LFT / Coag", fields: ["SGOT", "SGPT", "GGT", "PT/INR", "aPTT", "Fibrinogen", "D-dimer"] },
  {
    key: "screen",
    label: "Screening / Imaging",
    fields: [
      "Cranial USG",
      "Echocardiography",
      "Chest X-ray",
      "Abdominal X-ray",
      "USG abdomen",
      "MRI brain",
      "aEEG / EEG",
      "TSH (newborn screen)",
      "G6PD",
      "Expanded metabolic screen",
      "Hearing OAE",
      "BERA",
      "ROP screening",
      "Pulse oximetry CCHD screen",
    ],
  },
];

export const CARE_BUNDLE = [
  "Kangaroo mother care given",
  "Mother's own milk expression supported",
  "Oral care with colostrum",
  "Developmentally supportive positioning (nesting)",
  "Cluster care / minimal handling",
  "Noise & light protection",
  "Non-nutritive sucking",
  "Pain assessment (NIPS/PIPP) done",
  "Hand hygiene / CLABSI bundle checked",
  "Ventilator bundle (head end up 30°) checked",
  "ETT position confirmed",
  "Line site inspected – healthy",
  "Skin care / emollient applied",
  "Daily weight recorded",
  "Head circumference / length weekly",
  "Parents counselled today",
  "Consent taken (procedure / blood)",
  "Lactation counselling done",
  "Immunisation given (BCG / OPV / HepB)",
  "Physiotherapy / feeding therapy",
  "Family participatory care session",
];

export const DISCHARGE_CRITERIA = [
  "Maintaining temperature in open cot 24 h",
  "Weight gain ≥15 g/kg/day for 3 days",
  "Full oral / breast feeds, no tube",
  "No apnoea / bradycardia ≥5–7 days off caffeine",
  "Off oxygen / stable on home O2 plan",
  "Newborn screening completed",
  "Hearing screen done",
  "ROP screening complete / follow up fixed",
  "Immunisation up to date",
  "Cranial USG / neuro imaging done",
  "Parents trained – feeding, danger signs, KMC",
  "CPR / danger sign counselling completed",
  "High risk follow-up appointment given",
  "Discharge summary & medications explained",
];

export const NURSING_PARAMS = [
  "Heart rate",
  "Respiratory rate",
  "SpO₂ (pre/post ductal)",
  "Temperature (axillary/skin)",
  "Blood pressure / MAP",
  "Capillary refill time",
  "Perfusion index",
  "Blood sugar",
  "Pain score (NIPS / PIPP-R / N-PASS)",
  "Silverman-Anderson / Downes score",
  "Apnoea, bradycardia, desaturation count",
  "Fluid intake (ml/kg/day)",
  "Enteral volume (ml/kg/day)",
  "Urine output (ml/kg/hr)",
  "Stool frequency & character",
  "Gastric residual volume",
  "Abdominal girth",
  "Daily weight / weight change %",
  "Incubator temp & humidity",
  "Ventilator parameters & alarms",
  "Line site & day count",
  "Phototherapy hours / irradiance",
  "Sedation / withdrawal score",
];

export const SHIFTS = ["Morning (8–2)", "Evening (2–8)", "Night (8–8)"];
export const ILLNESS = ["stable", "guarded", "critical", "ready"] as const;
export const ACUITY_META: Record<string, { label: string; cls: string; dot: string }> = {
  critical: { label: "Critical / Unstable", cls: "bg-rose-500/15 text-rose-300 border-rose-500/40", dot: "bg-rose-400" },
  guarded: { label: "Guarded / Watcher", cls: "bg-amber-500/15 text-amber-300 border-amber-500/40", dot: "bg-amber-400" },
  stable: { label: "Stable", cls: "bg-emerald-500/15 text-emerald-300 border-emerald-500/40", dot: "bg-emerald-400" },
  ready: { label: "Ready for discharge", cls: "bg-sky-500/15 text-sky-300 border-sky-500/40", dot: "bg-sky-400" },
};

export const CONTINGENCY_PRESETS = [
  "If desaturation → check ETT position, suction, increase FiO₂ 10%, inform SR",
  "If apnoea >2 episodes/hr → escalate to NIPPV, load caffeine",
  "If MAP < gestational age → 10 ml/kg NS bolus, start dopamine 5 µg/kg/min",
  "If seizure → loading phenobarbitone 20 mg/kg, check sugar & calcium",
  "If sugar <45 mg/dL → 2 ml/kg D10 bolus, increase GIR by 2",
  "If abdominal distension / bloody stool → stop feeds, AXR, inform consultant",
  "If temp <36.5 °C → increase warmer setting, check sepsis",
  "If bleeding from site → send coagulation, vitamin K, inform on-call",
  "If extubation fails → re-intubate with size as charted, inform consultant",
  "If parents ask prognosis → consultant to counsel, do not discuss alone",
];

export const ACTION_PRESETS = [
  "Send ABG at 6 am",
  "Repeat CRP & CBC after 24 h",
  "Chase blood culture report",
  "Weigh baby and recalculate fluids",
  "Increase feeds by 20 ml/kg/day if tolerating",
  "Wean FiO₂ to keep SpO₂ 90–95%",
  "Trial off CPAP after 2 h",
  "Plan extubation post caffeine",
  "Serum bilirubin at 8 am",
  "Cranial USG today",
  "Echo today",
  "ROP screening today",
  "Remove UVC (day 7)",
  "Change to oral antibiotics / stop day 5",
  "Counsel parents with consultant",
  "Start KMC ≥ 4 hours",
  "Book discharge teaching session",
];
