export type PediatricDrugGroup = "Antimicrobials" | "Respiratory" | "Cardiotonic / diuretic" | "Neurology / sedation" | "Analgesic / anti-inflammatory" | "Gastro / allergy" | "Supplements" | "Other";
export type PediatricRuleUnit = "mg/kg/dose" | "mg/kg/day" | "mg/kg/24 h" | "mcg/kg/day" | "units/kg/day" | "mg/m2/day" | "mg/m2/dose" | "fixed";

export type PediatricDoseInput = { weightKg: number; ageYears: number; heightCm?: number; strength?: number };
export type PediatricRegimen = { condition: string; regimen: string; rule?: { low: number; high?: number; unit: PediatricRuleUnit; frequency: string; route?: string; fixedUnit?: string; fixedAmount?: number } };
export type PediatricDrug = { id: string; name: string; group: PediatricDrugGroup; strengthUnit?: "mg/mL" | "mcg/mL" | "mEq/mL" | "units/mL" | "mL"; defaultStrength?: number; regimens: PediatricRegimen[] };
export type PediatricDoseResult = { drug: string; dose: string; calculatedAmount?: string; frequency: string; route?: string; volume?: string; rule: string; caution: string };

const round = (n: number, digits = 2) => Math.round(n * 10 ** digits) / 10 ** digits;
const range = (low: number, high?: number) => high == null || low === high ? `${round(low)}` : `${round(low)}–${round(high)}`;
const amount = (dose: number, weight: number, unit: string) => `${round(dose * weight)} ${unit}`;
const resultUnit = (unit: PediatricRuleUnit) => unit.startsWith("mcg") ? "mcg" : unit.startsWith("units") ? "units" : "mg";
const bsa = (input: PediatricDoseInput) => input.heightCm && input.heightCm > 0 ? Math.sqrt(input.heightCm * input.weightKg / 3600) : null;
const genericCaution = "Verify indication, age band, renal/hepatic function, allergy status, maximum dose and local paediatric formulary before administration.";

function calculateDrug(drug: PediatricDrug, input: PediatricDoseInput, regimen: PediatricRegimen): PediatricDoseResult {
  const rule = regimen.rule;
  if (!rule) return { drug: drug.name, dose: regimen.regimen, frequency: "See selected chart regimen", rule: regimen.condition, caution: "This row contains indication-specific or non-weight dosing; verify the selected regimen manually." };
  if (rule.unit === "fixed") {
    const fixedUnit = rule.fixedUnit ?? "mg";
    const low = rule.fixedAmount ?? rule.low;
    const high = rule.high;
    const perKg = fixedUnit.includes("/kg");
    const patientLow = perKg ? low * input.weightKg : low;
    const patientHigh = high == null ? undefined : perKg ? high * input.weightKg : high;
    const patientUnit = perKg ? fixedUnit.replace("/kg", "") : fixedUnit;
    const calculatedAmount = `${range(patientLow, patientHigh)} ${patientUnit}`;
    const baseUnit = fixedUnit.split("/")[0];
    const strength = input.strength;
    const canConvertToVolume = strength != null && strength > 0 && ["mg", "mcg", "mEq", "IU", "U", "units"].includes(baseUnit);
    const volume = canConvertToVolume ? `${range(patientLow / strength, patientHigh == null ? undefined : patientHigh / strength)} mL` : undefined;
    return { drug: drug.name, dose: `${range(low, high)} ${fixedUnit}`, calculatedAmount, frequency: rule.frequency, route: rule.route, volume, rule: regimen.condition, caution: genericCaution };
  }
  const factor = rule.unit.startsWith("mg/m2") ? bsa(input) : input.weightKg;
  if (factor == null) return { drug: drug.name, dose: `${range(rule.low, rule.high)} ${rule.unit}`, frequency: rule.frequency, route: rule.route, rule: regimen.condition, caution: "Enter height to calculate a body-surface-area dose, then verify the result against the indication-specific chart row." };
  const unit = resultUnit(rule.unit);
  const calculated = rule.high == null ? amount(rule.low, factor, unit) : `${range(rule.low * factor, rule.high * factor)} ${unit}`;
  const concentration = input.strength && input.strength > 0 ? `${range((rule.low * factor) / input.strength, rule.high == null ? undefined : (rule.high * factor) / input.strength)} mL` : undefined;
  return { drug: drug.name, dose: `${range(rule.low, rule.high)} ${rule.unit}`, calculatedAmount: calculated, frequency: rule.frequency, route: rule.route, volume: concentration, rule: `${regimen.condition}${rule.unit.startsWith("mg/m2") ? `; BSA ${round(factor, 2)} m²` : ""}`, caution: genericCaution };
}

const r = (condition: string, regimen: string, rule?: PediatricRegimen["rule"]): PediatricRegimen => ({ condition, regimen, rule });
const kgDose = (low: number, high: number | undefined, frequency: string, route = "PO / IV"): PediatricRegimen["rule"] => ({ low, high, unit: "mg/kg/dose", frequency, route });
const kgDay = (low: number, high: number | undefined, frequency: string, route = "PO / IV"): PediatricRegimen["rule"] => ({ low, high, unit: "mg/kg/day", frequency, route });
const mcgDay = (low: number, high: number | undefined, frequency: string, route = "PO / IV"): PediatricRegimen["rule"] => ({ low, high, unit: "mcg/kg/day", frequency, route });
const bsaDay = (low: number, high: number | undefined, frequency: string, route = "PO / IV"): PediatricRegimen["rule"] => ({ low, high, unit: "mg/m2/day", frequency, route });

function drug(id: string, name: string, group: PediatricDrugGroup, regimens: PediatricRegimen[], strengthUnit: PediatricDrug["strengthUnit"] = "mg/mL", defaultStrength?: number): PediatricDrug {
  return { id, name, group, regimens, strengthUnit, defaultStrength };
}

export const PEDIATRIC_DRUGS: PediatricDrug[] = [
  drug("acyclovir", "Acyclovir", "Antimicrobials", [
    r("HSV encephalitis, 3 mo–12 yr", "60 mg/kg/24 h ÷ Q8 h IV for 14–21 days; some experts use 45 mg/kg/24 h", kgDay(60, 60, "Q8 h; 14–21 days", "IV")),
    r("HSV encephalitis, ≥12 yr", "30 mg/kg/24 h ÷ Q8 h IV", kgDay(30, 30, "Q8 h", "IV")),
    r("Mucocutaneous HSV, initial infection", "IV 15 mg/kg/24 h or 750 mg/m²/24 h Q8 h × 5–7 days", kgDay(15, 15, "Q8 h; 5–7 days", "IV")),
    r("Mucocutaneous HSV, oral", "40–80 mg/kg/24 h Q6–8 h for 5–10 days; max 1000 mg/24 h", kgDay(40, 80, "Q6–8 h; 5–10 days", "PO")),
    r("Zoster", "IV 30 mg/kg/24 h Q8 h × 7–10 days", kgDay(30, 30, "Q8 h; 7–10 days", "IV")),
    r("Varicella, ≥2 yr", "IV 30 mg/kg/24 h Q8 h or PO 80 mg/kg/24 h QID × 5 days", kgDay(30, 80, "QID / Q8 h; 5–10 days", "PO / IV")),
  ]),
  drug("amikacin-paed", "Amikacin", "Antimicrobials", [r("Antibiotic", "15–20 mg/kg/day Q12–24 h", kgDay(15, 20, "Q12–24 h", "IV"))]),
  drug("ampicillin-paed", "Ampicillin", "Antimicrobials", [r("Routine infection", "IV 25–50 mg/kg/dose Q6–8 h", kgDose(25, 50, "Q6–8 h", "IV")), r("Severe infection", "50–100 mg/kg/dose", kgDose(50, 100, "Per severe-infection protocol", "IV"))]),
  drug("amphotericin-b", "Amphotericin B (conventional)", "Antimicrobials", [r("Antifungal", "IV 0.5–1 mg/kg/dose Q24 h", kgDose(0.5, 1, "Q24 h", "IV"))]),
  drug("liposomal-amphotericin-b", "Amphotericin B (liposomal)", "Antimicrobials", [r("Antifungal", "IV 3–5 mg/kg/day Q24 h", kgDay(3, 5, "Q24 h", "IV"))]),
  drug("amoxicillin", "Amoxicillin", "Antimicrobials", [r("Neonate ≤3 mo", "PO 20–30 mg/kg/24 h ÷ Q12 h", kgDay(20, 30, "Q12 h", "PO")), r("Child", "PO 25–50 mg/kg/24 h ÷ Q8–12 h", kgDay(25, 50, "Q8–12 h", "PO"))]),
  drug("amoxicillin-clavulanate-paed", "Amoxicillin + clavulanate", "Antimicrobials", [r("Oral neonate", "15 mg amoxicillin/kg/dose every 12 h", kgDose(15, 15, "Q12 h", "PO")), r("IV neonate", "25–30 mg amoxicillin/kg/dose every 12 h", kgDose(25, 30, "Q12 h", "IV")), r("Mild/moderate infection", "40–80 mg/kg/24 h Q6–8 h", kgDay(40, 80, "Q6–8 h", "PO")), r("Severe/resistant infection", "80–90 mg/kg/day Q12 h", kgDay(80, 90, "Q12 h", "PO"))]),
  drug("azithromycin", "Azithromycin", "Antimicrobials", [r("Antibiotic", "PO 5–12 mg/kg/dose", kgDose(5, 12, "Per indication", "PO")), r("IV", "10 mg/kg once daily; max 500 mg/dose", kgDose(10, 10, "OD; max 500 mg/dose", "IV"))]),
  drug("aztreonam", "Aztreonam", "Antimicrobials", [r("Routine", "IV 90–150 mg/kg/day Q6–8 h", kgDay(90, 150, "Q6–8 h", "IV")), r("Cystic fibrosis", "200 mg/kg/day Q6 h; max 8 g/day", kgDay(200, 200, "Q6 h; max 8 g/day", "IV"))]),
  drug("cefepime", "Cefepime", "Antimicrobials", [r("Non-Pseudomonas infection", "IM/IV 50 mg/kg/dose every 12 h; max 2,000 mg/dose", kgDose(50, 50, "Q12 h; max 2 g/dose", "IM / IV")), r("Pseudomonas infection", "IM/IV 50 mg/kg/dose every 8 h; max 2,000 mg/dose", kgDose(50, 50, "Q8 h; max 2 g/dose", "IM / IV"))]),
  drug("cefixime", "Cefixime", "Antimicrobials", [r("Antibiotic", "PO 8 mg/kg/day OD or BD", kgDay(8, 8, "OD or BD", "PO")), r("Enteric fever", "20 mg/kg/day BD or OD", kgDay(20, 20, "OD or BD", "PO"))]),
  drug("cefpodoxime", "Cefpodoxime proxetil", "Antimicrobials", [r("Antibiotic", "PO 5 mg/kg/dose every 12 h; max 200 mg/dose", kgDose(5, 5, "Q12 h; max 200 mg/dose", "PO"))]),
  drug("cefoperazone-sulbactam", "Cefoperazone + sulbactam", "Antimicrobials", [r("Antibiotic", "IV 80–160 mg/kg/day of cefoperazone Q6 h", kgDay(80, 160, "Q6 h", "IV"))]),
  drug("cefotaxime-paed", "Cefotaxime", "Antimicrobials", [r("Routine", "IV 150–180 mg/kg/day Q6–8 h", kgDay(150, 180, "Q6–8 h", "IV")), r("Severe infection", "IV 200–300 mg/kg/day", kgDay(200, 300, "Per severe-infection protocol", "IV"))]),
  drug("ceftazidime-avibactam", "Ceftazidime + avibactam", "Antimicrobials", [r("Antibiotic", "Ceftazidime IV 30–50 mg/kg/dose Q8 h", kgDose(30, 50, "Q8 h", "IV")), r("Cystic fibrosis", "150–400 mg/kg/day Q6–8 h", kgDay(150, 400, "Q6–8 h", "IV"))]),
  drug("ceftaroline", "Ceftaroline fosamil", "Antimicrobials", [r("Bloodstream infection, >2 mo", "IV 10 mg/kg/dose Q8–12 h", kgDose(10, 10, "Q8–12 h", "IV")), r("≤6 months", "IV 24–30 mg/kg/day Q8 h", kgDay(24, 30, "Q8 h", "IV"))]),
  drug("ceftriaxone", "Ceftriaxone", "Antimicrobials", [r("Routine", "IV 50–75 mg/kg/day single dose or divided Q12 h; max 2 g/day", kgDay(50, 75, "OD or Q12 h; max 2 g/day", "IV")), r("CNS infection", "100 mg/kg/day single dose or Q12 h; max 4 g/day", kgDay(100, 100, "OD or Q12 h; max 4 g/day", "IV"))]),
  drug("cefuroxime", "Cefuroxime", "Antimicrobials", [r("IV / IM", "100–150 mg/kg/day divided Q8 h; max 6 g/day", kgDay(100, 150, "Q8 h; max 6 g/day", "IV / IM")), r("Oral", "20–30 mg/kg/day divided Q12 h; max 1 g/day", kgDay(20, 30, "Q12 h; max 1 g/day", "PO"))]),
  drug("ciprofloxacin", "Ciprofloxacin", "Antimicrobials", [r("IV", "10 mg/kg/dose Q8–12 h; max 400 mg/dose", kgDose(10, 10, "Q8–12 h; max 400 mg/dose", "IV")), r("Oral immediate release", "15 mg/kg/dose Q12 h; max 500 mg/dose", kgDose(15, 15, "Q12 h; max 500 mg/dose", "PO"))]),
  drug("clindamycin", "Clindamycin", "Antimicrobials", [r("Routine", "IV 20–40 mg/kg/day divided Q6–8 h; max 2700 mg/day", kgDay(20, 40, "Q6–8 h; max 2700 mg/day", "IV")), r("Severe infection", "IV 25–40 mg/kg/day Q6–8 h", kgDay(25, 40, "Q6–8 h", "IV")), r("Oral", "10–25 mg/kg/day Q6–8 h", kgDay(10, 25, "Q6–8 h", "PO"))]),
  drug("colistin", "Colistin", "Antimicrobials", [r("IV", "90,000–180,000 units/kg/day Q8–12 h", { low: 90000, high: 180000, unit: "units/kg/day", frequency: "Q8–12 h", route: "IV" }), r("Inhaled <2 yr", "50,000–1,000,000 units BD", { low: 50000, high: 1000000, unit: "units/kg/day", frequency: "BD", route: "Inhaled" })], "units/mL"),
  drug("daptomycin", "Daptomycin", "Antimicrobials", [r("<2 yr", "IV 10–12 mg/kg/dose Q24 h", kgDose(10, 12, "Q24 h", "IV")), r("2 to <7 yr", "IV 9–12 mg/kg/dose Q24 h", kgDose(9, 12, "Q24 h", "IV")), r("7 to <12 yr", "IV 7–9 mg/kg/dose Q24 h", kgDose(7, 9, "Q24 h", "IV")), r("≥12 yr", "IV 5–7 mg/kg/dose Q24 h", kgDose(5, 7, "Q24 h", "IV"))]),
  drug("doxycycline", "Doxycycline", "Antimicrobials", [r("Antibiotic", "IV / PO 2.2 mg/kg/dose Q12 h; max 100 mg/dose", kgDose(2.2, 2.2, "Q12 h; max 100 mg/dose", "PO / IV"))]),
  drug("fluconazole-paed", "Fluconazole", "Antimicrobials", [r("Invasive candidiasis", "IV/PO 12 mg/kg/day Q24 h", kgDay(12, 12, "Q24 h", "IV / PO")), r("Prophylaxis", "IV 3–6 mg/kg/day", kgDay(3, 6, "Per prophylaxis protocol", "IV"))]),
  drug("gentamicin-paed", "Gentamicin", "Antimicrobials", [r("Conventional IM/IV", "2–2.5 mg/kg/dose every 8 h", kgDose(2, 2.5, "Q8 h", "IM / IV")), r("Extended interval", "IV 5–7.5 mg/kg/dose Q24 h", kgDose(5, 7.5, "Q24 h", "IV"))]),
  drug("levofloxacin", "Levofloxacin", "Antimicrobials", [r("Infants ≥6 mo and children <5 yr", "PO/IV 8–10 mg/kg/dose BD", kgDose(8, 10, "BD", "PO / IV")), r("Children ≥5 yr and adolescents", "See selected local regimen", undefined)]),
  drug("linezolid", "Linezolid", "Antimicrobials", [r("Infants and children <12 yr", "PO/IV 10 mg/kg/dose Q8 h; max 600 mg/dose", kgDose(10, 10, "Q8 h; max 600 mg/dose", "PO / IV")), r("≥12 yr", "PO/IV 600 mg Q12 h", { low: 600, unit: "fixed", frequency: "Q12 h", route: "PO / IV", fixedUnit: "mg", fixedAmount: 600 })]),
  drug("meropenem-paed", "Meropenem", "Antimicrobials", [r("Routine", "IV 20–40 mg/kg/dose Q8 h", kgDose(20, 40, "Q8 h", "IV")), r("Severe infection", "IV 40 mg/kg/dose Q8 h", kgDose(40, 40, "Q8 h", "IV"))]),
  drug("metronidazole-paed", "Metronidazole", "Antimicrobials", [r("Oral", "15–50 mg/kg/day divided Q8 h; max 2250 mg/day", kgDay(15, 50, "Q8 h; max 2250 mg/day", "PO")), r("IV", "22.5–40 mg/kg/day divided Q6–8 h; max 4000 mg/day", kgDay(22.5, 40, "Q6–8 h; max 4 g/day", "IV"))]),
  drug("ofloxacin", "Ofloxacin", "Antimicrobials", [r("Antibiotic", "Oral 15 mg/kg/day divided Q12 h", kgDay(15, 15, "Q12 h", "PO"))]),
  drug("piperacillin-tazobactam-paed", "Piperacillin + tazobactam", "Antimicrobials", [r("Routine", "IV 100 mg/kg/dose of piperacillin Q8 h; max 400 mg/kg/day", kgDose(100, 100, "Q8 h; max 400 mg/kg/day", "IV"))]),
  drug("polymyxin-b", "Polymyxin B", "Antimicrobials", [r("Antibiotic", "IV 25,000–30,000 units/kg/day Q12 h; max 40,000 units/kg/day", { low: 25000, high: 30000, unit: "units/kg/day", frequency: "Q12 h", route: "IV" })], "units/mL"),
  drug("teicoplanin", "Teicoplanin", "Antimicrobials", [r("Loading", "IV 1.5–3 mg/kg/dose Q12 h for 3 doses", kgDose(1.5, 3, "Q12 h ×3", "IV")), r("Maintenance", "IV 6–10 mg/kg/dose Q24 h", kgDose(6, 10, "Q24 h", "IV"))]),
  drug("tigecycline", "Tigecycline", "Antimicrobials", [r("Loading", "IV 1.5–3 mg/kg/dose", kgDose(1.5, 3, "Loading; local protocol", "IV")), r("Maintenance", "IV 1.2 mg/kg Q12 h", kgDose(1.2, 1.2, "Q12 h", "IV"))]),
  drug("trimethoprim-sulfamethoxazole", "Trimethoprim + sulphamethoxazole", "Antimicrobials", [r("Antibiotic", "Oral/IV 8–12 mg TMP/kg/day divided Q12 h; max 320 mg TMP/dose", kgDay(8, 12, "Q12 h", "PO / IV"))]),
  drug("vancomycin-paed", "Vancomycin", "Antimicrobials", [r("Routine", "IV 10 mg/kg/dose", kgDose(10, 10, "Per level-guided protocol", "IV")), r("CNS infection", "IV 15 mg/kg/dose Q6 h; max 4 g/day", kgDose(15, 15, "Q6 h; max 4 g/day", "IV"))]),
  drug("baclofen", "Baclofen", "Neurology / sedation", [r("Muscle relaxant", "PO 0.75–2 mg/kg/day Q8 h", kgDay(0.75, 2, "Q8 h", "PO"))]),
  drug("caffeine-citrate", "Caffeine citrate", "Respiratory", [r("Apnoea of prematurity", "IV 10–20 mg/kg slow infusion over 30 min", kgDose(10, 20, "Slow infusion over 30 min", "IV")), r("Maintenance oral", "5 mg/kg/day single or divided doses", kgDay(5, 5, "OD / divided", "PO"))]),
  drug("calcium-gluconate", "Calcium gluconate", "Cardiotonic / diuretic", [r("Maintenance", "2–4 mL/kg/day Q6 h", { low: 2, high: 4, unit: "fixed", frequency: "Q6 h", route: "IV", fixedUnit: "mL/kg/day" }), r("Hypocalcaemia", "1–2 mL/kg slow IV push", { low: 1, high: 2, unit: "fixed", frequency: "Slow IV push", route: "IV", fixedUnit: "mL/kg/dose" }), r("Cardiac arrest", "0.2–0.5 mL/kg IV", { low: 0.2, high: 0.5, unit: "fixed", frequency: "Emergency", route: "IV", fixedUnit: "mL/kg" })], "mL"),
  drug("potassium-chloride", "Potassium chloride", "Cardiotonic / diuretic", [r("Hypokalaemia", "1–2 mEq/kg/day Q8 h oral", { low: 1, high: 2, unit: "fixed", frequency: "Q8 h oral", route: "PO", fixedUnit: "mEq/kg/day" })], "mEq/mL"),
  drug("sodium-bicarbonate", "Sodium bicarbonate", "Cardiotonic / diuretic", [r("Metabolic acidosis", "IV 1–2 mEq/kg/dose after dilution", { low: 1, high: 2, unit: "fixed", frequency: "After dilution", route: "IV", fixedUnit: "mEq/kg/dose" })], "mEq/mL"),
  drug("ursodeoxycholic-acid-paed", "Ursodeoxycholic acid", "Gastro / allergy", [r("Hepatic dysfunction / biliary obstruction", "10–20 mg/kg/day Q8 h", kgDay(10, 20, "Q8 h", "PO"))]),
  drug("zinc", "Zinc", "Supplements", [r("Infants: deficiency", "0.5 mg/day", { low: 0.5, unit: "fixed", frequency: "OD", route: "PO", fixedUnit: "mg/day" }), r("<6 months: acute/persistent diarrhoea", "10 mg/day", { low: 10, unit: "fixed", frequency: "OD ×14 days", route: "PO", fixedUnit: "mg/day" }), r(">6 months: acute/persistent diarrhoea", "20 mg/day ×14 days", { low: 20, unit: "fixed", frequency: "OD ×14 days", route: "PO", fixedUnit: "mg/day" }), r("Acrodermatitis enteropathica", "6 mg/kg/dose", kgDose(6, 6, "Per deficiency protocol", "PO"))]),
  drug("propranolol", "Propranolol hydrochloride", "Cardiotonic / diuretic", [r("Hypertension", "0.5–1 mg/kg/day Q6–12 h; max 4 mg/kg/day", kgDay(0.5, 1, "Q6–12 h; max 4 mg/kg/day", "PO")), r("Arrhythmia / cyanotic spells", "2–6 mg/kg/day Q6–8 h", kgDay(2, 6, "Q6–8 h", "PO"))]),
  drug("vitamin-c", "Vitamin C (ascorbic acid)", "Supplements", [r("Daily requirement, term", "0–6 mo: 40 mg/day", { low: 40, unit: "fixed", frequency: "OD", route: "PO", fixedUnit: "mg/day" }), r("Daily requirement, term", "1–3 yr: 15 mg/day", { low: 15, unit: "fixed", frequency: "OD", route: "PO", fixedUnit: "mg/day" }), r("Scurvy", "100–300 mg/24 h OD–BID for 2 weeks", { low: 100, high: 300, unit: "fixed", frequency: "OD–BID ×2 weeks", route: "PO / IM / IV / SC", fixedUnit: "mg/day" })]),
  drug("vitamin-d3", "Vitamin D3 (cholecalciferol)", "Supplements", [r("VLBW maintenance", "Infants 800 IU/day; birth–12 mo 400 IU/day", { low: 400, high: 800, unit: "fixed", frequency: "OD", route: "PO", fixedUnit: "IU/day" }), r("Deficiency, preterm", "1000 IU/day", { low: 1000, unit: "fixed", frequency: "OD", route: "PO", fixedUnit: "IU/day" }), r("Deficiency, 1–18 yr", "3000–4000 IU/day ×90 days", { low: 3000, high: 4000, unit: "fixed", frequency: "OD ×90 days", route: "PO", fixedUnit: "IU/day" })], "mL"),
  drug("vitamin-k", "Vitamin K", "Supplements", [r("Term prophylaxis", "1 mg IM", { low: 1, unit: "fixed", frequency: "Once", route: "IM", fixedUnit: "mg" }), r("Preterm prophylaxis", "0.5 mg IM", { low: 0.5, unit: "fixed", frequency: "Once", route: "IM", fixedUnit: "mg" }), r("Therapeutic", "5–10 mg/dose SC/IM/IV; max single dose 10 mg", { low: 5, high: 10, unit: "fixed", frequency: "Per indication", route: "SC / IM / IV", fixedUnit: "mg" })]),
  drug("triclofos", "Triclofos", "Neurology / sedation", [r("Sedation", "20 mg/kg/dose", kgDose(20, 20, "Per sedation protocol", "PO")), r("1–5 yr", "250–500 mg", { low: 250, high: 500, unit: "fixed", frequency: "Per sedation protocol", route: "PO", fixedUnit: "mg" }), r("6–12 yr", "0.5–1 g", { low: 500, high: 1000, unit: "fixed", frequency: "Per sedation protocol", route: "PO", fixedUnit: "mg" })]),
  drug("folic-acid", "Folic acid", "Supplements", [r("Initial", "15 mcg/kg/dose; max 50 mcg/24 h; 1 mg/dose", mcgDay(15, 15, "Initial; max 50 mcg/24 h", "PO")), r("Maintenance", "30–45 mcg/24 h OD or 0.1–0.4 mg/24 h OD", { low: 30, high: 45, unit: "fixed", frequency: "OD", route: "PO", fixedUnit: "mcg/day" })], "mcg/mL"),
  drug("iron-paed", "Iron", "Supplements", [r("Prophylaxis", "1–2 mg/kg/day OD / Q12 h", kgDay(1, 2, "OD / Q12 h", "PO")), r("INH neuropathy", "3–6 mg/kg/day OD / Q12 h", kgDay(3, 6, "OD / Q12 h", "PO")), r("Preterm <32 wk", "2–4 mg/kg/day", kgDay(2, 4, "OD", "PO"))]),
  drug("vitamin-b1", "Vitamin B1", "Supplements", [r("Daily requirement", "0.1–1.2 mg or 0.5 mg/1000 kcal", { low: 0.1, high: 1.2, unit: "fixed", frequency: "OD", route: "PO", fixedUnit: "mg/day" }), r("Beriberi", "10–25 mg/day IM/IV; 10–50 mg/day PO for 2 weeks", { low: 10, high: 50, unit: "fixed", frequency: "Per indication", route: "PO / IM / IV", fixedUnit: "mg/day" }), r("Metabolic disease", "100 mg Q8 h", { low: 100, unit: "fixed", frequency: "Q8 h", route: "PO / IV", fixedUnit: "mg/dose" })]),
  drug("vitamin-b2", "Vitamin B2", "Supplements", [r("Daily requirement", "0.1–2 mg or 1.2 mg/1000 kcal diet", { low: 0.1, high: 2, unit: "fixed", frequency: "OD", route: "PO", fixedUnit: "mg/day" }), r("Deficiency", "2.5–10 mg/day OD/BD PO", { low: 2.5, high: 10, unit: "fixed", frequency: "OD / BD", route: "PO", fixedUnit: "mg/day" })]),
  drug("pyridoxine", "Vitamin B6 (pyridoxine)", "Neurology / sedation", [r("General", "0.3–1.3 mg/kg/day PO/IM/IV", kgDay(0.3, 1.3, "OD", "PO / IM / IV")), r("INH neuropathy prevention", "10 mg/day (1 mg/kg/day)", kgDay(1, 1, "OD", "PO")), r("Pyridoxine-dependent seizures", "100 mg IV over 1 min; max 400 mg, followed by 50–100 mg/day", { low: 100, high: 100, unit: "fixed", frequency: "Emergency then maintenance", route: "IV", fixedUnit: "mg" })]),
  drug("vitamin-b12", "Vitamin B12 (cyanocobalamin)", "Supplements", [r("Physiological", "0.3–2 mcg/day", { low: 0.3, high: 2, unit: "fixed", frequency: "OD", route: "PO / IM", fixedUnit: "mcg/day" }), r("Therapeutic", "250–1000 mcg IM daily then weekly", { low: 250, high: 1000, unit: "fixed", frequency: "Daily then weekly", route: "IM", fixedUnit: "mcg" })], "mcg/mL"),
  drug("furosemide-paed", "Furosemide", "Cardiotonic / diuretic", [r("Neonate IM/IV", "0.5–1 mg/kg/dose Q8–24 h; max 2 mg/kg/dose", kgDose(0.5, 1, "Q8–24 h; max 2 mg/kg/dose", "IM / IV")), r("Infant/child oral", "1–3 mg/kg/dose OD/BD; max 6 mg/kg/dose", kgDose(1, 3, "OD / BD; max 6 mg/kg/dose", "PO")), r("IV infusion", "Start 0.05 mg/kg/hr and titrate", kgDay(0.05, 0.05, "Continuous infusion", "IV"))]),
  drug("spironolactone-paed", "Spironolactone", "Cardiotonic / diuretic", [r("Diuretics", "Neonate 1–3 mg/kg/24 h OD–BD; child 1–3.3 mg/kg/24 h BD–QID", kgDay(1, 3.3, "OD–QID", "PO")), r("Anti-hypertensive", "1–3.3 mg/kg/day Q6–12 h", kgDay(1, 3.3, "Q6–12 h", "PO"))]),
  drug("dexamethasone", "Dexamethasone", "Respiratory", [r("Anti-inflammatory", "Oral 0.05–0.5 mg/kg/day", kgDay(0.05, 0.5, "OD", "PO")), r("Cerebral oedema", "IM/IV 0.5 mg/kg/dose Q6 h", kgDose(0.5, 0.5, "Q6 h", "IM / IV")), r("Croup", "0.6 mg/kg STAT", kgDose(0.6, 0.6, "STAT", "PO / IM / IV")), r("Pulse therapy", "5 mg/kg slow infusion; max 100 mg", kgDose(5, 5, "Slow infusion; max 100 mg", "IV"))]),
  drug("hydrocortisone", "Hydrocortisone", "Respiratory", [r("Anti-inflammatory", "2.5–10 mg/kg/day Q6 h", kgDay(2.5, 10, "Q6 h", "PO / IV")), r("Status asthmaticus loading", "4–8 mg/kg/dose IV; max 250 mg", kgDose(4, 8, "Loading; max 250 mg", "IV")), r("Status asthmaticus maintenance", "8 mg/kg/24 h ÷ Q6 h IV", kgDay(8, 8, "Q6 h", "IV"))]),
  drug("methylprednisolone", "Methylprednisolone", "Respiratory", [r("Anti-inflammatory", "0.5–1.7 mg/kg/day", kgDay(0.5, 1.7, "OD / divided", "PO / IM / IV")), r("Emergency", "30 mg/kg IV bolus over 10–20 min", kgDose(30, 30, "Emergency bolus", "IV")), r("Pulse therapy", "30 mg/kg for 3–5 days", kgDose(30, 30, "OD ×3–5 days", "IV"))]),
  drug("prednisolone", "Prednisolone", "Respiratory", [r("Anti-inflammatory", "0.5–2 mg/kg/24 h PO OD–BID", kgDay(0.5, 2, "OD–BID", "PO")), r("Acute asthma", "2 mg/kg/24 h PO OD–BID ×5–7 days; max 80 mg/24 h", kgDay(2, 2, "OD–BID ×5–7 days; max 80 mg/day", "PO")), r("Infantile spasms", "2 mg/kg/day Q12 h for 2–6 weeks; taper", kgDay(2, 2, "Q12 h ×2–6 weeks", "PO"))]),
  drug("ipratropium", "Ipratropium bromide", "Respiratory", [r("Acute asthma <1 yr", "Neb 125 mcg", { low: 125, unit: "fixed", frequency: "Nebulised", route: "Neb", fixedUnit: "mcg" }), r("1–12 yr", "250 mcg", { low: 250, unit: "fixed", frequency: "Nebulised", route: "Neb", fixedUnit: "mcg" }), r(">12 yr", "500 mcg", { low: 500, unit: "fixed", frequency: "Nebulised", route: "Neb", fixedUnit: "mcg" })], "mcg/mL"),
  drug("digoxin-paed", "Digoxin", "Cardiotonic / diuretic", [r("Full-term neonate", "30 mcg/kg/day PO", mcgDay(30, 30, "OD / divided", "PO")), r("Children <2 yr", "40–50 mcg/kg/day", mcgDay(40, 50, "OD / divided", "PO")), r("2–10 yr", "30–40 mcg/kg/day", mcgDay(30, 40, "OD / divided", "PO")), r(">10 yr", "0.75–1.5 mg/day", { low: 0.75, high: 1.5, unit: "fixed", frequency: "OD / divided", route: "PO", fixedUnit: "mg/day" })], "mcg/mL"),
  drug("acetazolamide", "Acetazolamide", "Cardiotonic / diuretic", [r("Diuretics", "PO 5 mg/kg/dose OD or alternate days", kgDose(5, 5, "OD / alternate days", "PO")), r("Hydrocephalus", "20 mg/kg/24 h Q8 h; may increase to 100 mg/kg/24 h", kgDay(20, 100, "Q8 h", "PO / IV")), r("Glaucoma/high-altitude/epilepsy", "PO 8–30 mg/kg/24 h Q6–8 h", kgDay(8, 30, "Q6–8 h", "PO"))]),
  drug("levocetirizine", "Levocetirizine", "Gastro / allergy", [r("2–6 yr", "1.25 mg single dose", { low: 1.25, unit: "fixed", frequency: "Single / OD", route: "PO", fixedUnit: "mg" }), r(">6 yr", "2.5 mg single or two doses", { low: 2.5, unit: "fixed", frequency: "OD / divided", route: "PO", fixedUnit: "mg" })]),
  drug("pheniramine", "Pheniramine maleate", "Gastro / allergy", [r("Allergic rhinitis", "0.5 mg/kg/day Q8 h", kgDay(0.5, 0.5, "Q8 h", "PO / IM / IV"))]),
  drug("phenytoin-myotonia", "Phenytoin sodium", "Neurology / sedation", [r("Congenital myotonia / myotonic dystrophy", "4–8 mg/kg in two divided doses", kgDay(4, 8, "BD", "PO"))]),
  drug("salbutamol-myasthenia", "Salbutamol", "Respiratory", [r("Congenital myasthenia syndrome", "0.1–0.4 mg/kg/dose Q8 h", kgDose(0.1, 0.4, "Q8 h", "PO"))]),
  drug("simethicone", "Simethicone", "Gastro / allergy", [r("Children <2 yr", "20 mg QID; max 240 mg/day", { low: 20, unit: "fixed", frequency: "QID; max 240 mg/day", route: "PO", fixedUnit: "mg/dose" }), r("2–12 yr", "40 mg QID; max 500 mg/day", { low: 40, unit: "fixed", frequency: "QID; max 500 mg/day", route: "PO", fixedUnit: "mg/dose" })]),
  drug("levalbuterol", "Levosalbutamol", "Respiratory", [r("Rescue therapy, MDI", "2 puffs of 50 mcg Q4–6 h", { low: 100, unit: "fixed", frequency: "Q4–6 h", route: "MDI", fixedUnit: "mcg" }), r("Nebulisation", "0.075 mg/kg; minimum 1.25 mg, maximum 5 mg", kgDose(0.075, 0.075, "Q1–4 h ×3 then protocol", "Neb"))]),
  drug("montelukast", "Montelukast", "Respiratory", [r("6 mo–5 yr", "4 mg OD", { low: 4, unit: "fixed", frequency: "OD evening", route: "PO", fixedUnit: "mg" }), r("6–14 yr", "5 mg OD", { low: 5, unit: "fixed", frequency: "OD evening", route: "PO", fixedUnit: "mg" }), r(">14 yr", "10 mg OD", { low: 10, unit: "fixed", frequency: "OD evening", route: "PO", fixedUnit: "mg" })]),
  drug("salbutamol", "Salbutamol", "Respiratory", [r("Acute exacerbation MDI", "100 mcg/puff; 2–4 puffs at 20 min intervals, then Q4–6 h", { low: 2, high: 4, unit: "fixed", frequency: "MDI Q20 min then Q4–6 h", route: "MDI", fixedUnit: "puffs" }), r("Nebulisation", "0.15 mg/kg/dose; minimum 2.5 mg, maximum 5 mg", kgDose(0.15, 0.15, "Q20 min ×3 then Q2–6 h", "Neb"))]),
  drug("budesonide", "Budesonide", "Respiratory", [r("Very severe exacerbation", "0.5 mg/kg/hr continuous nebulisation", kgDay(0.5, 0.5, "Continuous nebulisation", "Neb")), r("Long-term asthma control", "100–800 mcg/day Q12 h", mcgDay(100, 800, "Q12 h", "Inhaled"))], "mcg/mL"),
  drug("ranitidine", "Ranitidine", "Gastro / allergy", [r("1–5 months", "1–2 mg/kg Q8 h; double for GERD", kgDose(1, 2, "Q8 h", "PO")), r("≥6 months", "2–4 mg/kg Q12 h", kgDose(2, 4, "Q12 h", "PO"))]),
  drug("pantoprazole", "Pantoprazole", "Gastro / allergy", [r("15–40 kg", "20 mg OD", { low: 20, unit: "fixed", frequency: "OD", route: "PO", fixedUnit: "mg" }), r(">40 kg", "40 mg OD", { low: 40, unit: "fixed", frequency: "OD", route: "PO", fixedUnit: "mg" })]),
  drug("heparin", "Heparin", "Cardiotonic / diuretic", [r("Thrombosis <1 yr", "75 IU/kg IV bolus followed by 28 IU/kg/hr", { low: 75, unit: "fixed", frequency: "Bolus then infusion", route: "IV", fixedUnit: "IU/kg" }), r("Thrombosis >1 yr", "20 IU/kg/hr IV infusion", { low: 20, unit: "fixed", frequency: "Continuous infusion", route: "IV", fixedUnit: "IU/kg/hr" }), r("Central line flush", "10 U/mL Q6–8 h", { low: 10, unit: "fixed", frequency: "Q6–8 h", route: "Line", fixedUnit: "U/mL" })], "units/mL"),
  drug("cetirizine", "Cetirizine dihydrochloride", "Gastro / allergy", [r("6 mo–2 yr", "2.5 mg OD", { low: 2.5, unit: "fixed", frequency: "OD", route: "PO", fixedUnit: "mg" }), r("2–6 yr", "2.5 mg OD or 5 mg OD", { low: 2.5, high: 5, unit: "fixed", frequency: "OD", route: "PO", fixedUnit: "mg" }), r(">6 yr", "5–10 mg OD", { low: 5, high: 10, unit: "fixed", frequency: "OD", route: "PO", fixedUnit: "mg" })]),
  drug("chlorpheniramine", "Chlorpheniramine maleate", "Gastro / allergy", [r("Children", "0.35 mg/kg/day Q4–6 h", kgDay(0.35, 0.35, "Q4–6 h", "PO")), r("1–6 yr", "1 mg PO Q4–6 h; max 6 mg/day", { low: 1, unit: "fixed", frequency: "Q4–6 h; max 6 mg/day", route: "PO", fixedUnit: "mg/dose" }), r("6–12 yr", "2 mg PO Q4–6 h; max 12 mg/day", { low: 2, unit: "fixed", frequency: "Q4–6 h; max 12 mg/day", route: "PO", fixedUnit: "mg/dose" })]),
  drug("fexofenadine", "Fexofenadine hydrochloride", "Gastro / allergy", [r("6 months–2 yr", "15–30 mg BD", { low: 15, high: 30, unit: "fixed", frequency: "BD", route: "PO", fixedUnit: "mg" })]),
  drug("domperidone-paed", "Domperidone", "Gastro / allergy", [r("Nausea/vomiting", "0.2–0.5 mg/kg/dose Q4–8 h", kgDose(0.2, 0.5, "Q4–8 h", "PO"))]),
  drug("ondansetron", "Ondansetron", "Gastro / allergy", [r("<4 yr", "2 mg Q4 h", { low: 2, unit: "fixed", frequency: "Q4 h", route: "PO", fixedUnit: "mg" }), r("4–11 yr", "4 mg Q4 h", { low: 4, unit: "fixed", frequency: "Q4 h", route: "PO", fixedUnit: "mg" }), r("≥12 yr", "8 mg Q4 h", { low: 8, unit: "fixed", frequency: "Q4 h", route: "PO", fixedUnit: "mg" }), r(">3 yr IV", "0.15–0.45 mg/kg/dose 30 min before and 4/8 h after emetogenic drugs", kgDose(0.15, 0.45, "Per emetogenic-drug protocol", "IV"))]),
  drug("lacosamide", "Lacosamide", "Neurology / sedation", [r("Adjunctive therapy", "Starting 1 mg/kg/day Q12 h; maintenance 2–12 mg/kg/day Q12 h", kgDay(1, 12, "Q12 h", "PO / IV"))]),
  drug("valproate", "Valproate sodium", "Neurology / sedation", [r("Broad spectrum", "10–15 mg/kg/day Q8–12 h; increase to max 60 mg/kg/day", kgDay(10, 15, "Q8–12 h", "PO")), r("Status epilepticus loading", "20 mg/kg followed by 5–10 mg/kg/dose Q8 h", kgDose(20, 20, "Loading then Q8 h", "IV"))]),
  drug("clobazam", "Clobazam", "Neurology / sedation", [r("Infant/child <2 yr", "0.5–1 mg/kg/24 h; max 5 mg/24 h PO ÷ BID", kgDay(0.5, 1, "BD", "PO")), r("2–16 yr", "Start 5 mg daily, increase every 5–7 days; max 40 mg/day", { low: 5, unit: "fixed", frequency: "OD then titrate", route: "PO", fixedUnit: "mg/day" })]),
  drug("fosphenytoin", "Fosphenytoin", "Neurology / sedation", [r("Loading", "10–15 mg/kg IV", kgDose(10, 15, "Loading", "IV")), r("Maintenance", "4–8 mg/kg/day IV/IM", kgDay(4, 8, "OD / divided", "IV / IM")), r("IV infusion", "3 mg/kg/min", kgDose(3, 3, "Infusion rate", "IV"))]),
  drug("levetiracetam", "Levetiracetam", "Neurology / sedation", [r("Infant 1–5 mo", "7 mg/kg/dose PO BID", kgDose(7, 7, "BD", "PO")), r("Infant ≥6 mo–child 3 yr", "10 mg/kg/dose PO BID", kgDose(10, 10, "BD", "PO")), r("Child 4–15 yr", "10 mg/kg/dose PO BID", kgDose(10, 10, "BD", "PO"))]),
  drug("phenytoin", "Phenytoin", "Neurology / sedation", [r("Loading", "15–20 mg/kg at rate 1 mg/kg/min", kgDose(15, 20, "Loading infusion", "IV")), r("Maintenance", "5–8 mg/kg/day Q8–12 h or OD", kgDay(5, 8, "OD–Q12 h", "PO / IV"))]),
  drug("midazolam", "Midazolam", "Neurology / sedation", [r("Status epilepticus", "0.2 mg/kg IM/IV bolus followed by 0.1–0.2 mg/kg/hr", kgDose(0.2, 0.2, "Bolus then infusion", "IM / IV")), r("Neonate ventilation", "0.05–0.15 mg/kg/dose Q1–2 h or infusion 0.2–1 mcg/kg/min", kgDose(0.05, 0.15, "Q1–2 h / infusion", "IV")), r("Sedation", "0.05–0.1 mg/kg over 2 min, repeat to 0.2 mg/kg", kgDose(0.05, 0.1, "Titrate", "IV"))]),
  drug("tramadol", "Tramadol", "Analgesic / anti-inflammatory", [r("Pain", "1–2 mg/kg Q4–6 h; max 400 mg/24 h; avoid below 14 yr", kgDose(1, 2, "Q4–6 h; max 400 mg/day", "PO / IV"))]),
  drug("aspirin", "Aspirin", "Analgesic / anti-inflammatory", [r("Analgesic/antipyretic", "10–15 mg/kg/dose Q4–6 h; total 60–80 mg/kg/24 h", kgDose(10, 15, "Q4–6 h", "PO / PR")), r("Kawasaki", "80–100 mg/kg/24 h QID then 3–5 mg/kg/24 h", kgDay(80, 100, "QID then OD", "PO"))]),
  drug("albendazole", "Albendazole", "Other", [r("Pinworm/roundworm 1–2 yr", "200 mg single dose", { low: 200, unit: "fixed", frequency: "Single; repeat after 2 weeks if indicated", route: "PO", fixedUnit: "mg" }), r("≥2 yr", "400 mg single dose", { low: 400, unit: "fixed", frequency: "Single; repeat after 2 weeks if indicated", route: "PO", fixedUnit: "mg" }), r("Giardiasis", "400 mg OD ×5 days", { low: 400, unit: "fixed", frequency: "OD ×5 days", route: "PO", fixedUnit: "mg" }), r("Neurocysticercosis", "15 mg/kg/day in two divided doses ×7–30 days", kgDay(15, 15, "BD; duration-specific", "PO"))]),
  drug("atropine", "Atropine sulfate", "Cardiotonic / diuretic", [r("Symptomatic bradycardia", "0.025 mg/kg/dose SC/IV; minimum 0.1 mg/dose", kgDose(0.025, 0.025, "Emergency / repeat per protocol", "SC / IV")), r("Organophosphate poisoning", "0.05 mg/kg IV repeated Q3–5 min", kgDose(0.05, 0.05, "Q3–5 min", "IV")), r("Pre-anaesthesia <5 kg", "0.02 mg/kg/dose", kgDose(0.02, 0.02, "Pre-anaesthetic", "IM / IV"))]),
  drug("diclofenac", "Diclofenac sodium", "Analgesic / anti-inflammatory", [r("Post-traumatic/inflammatory conditions", "1–3 mg/kg/day Q8 h; max 150 mg/day", kgDay(1, 3, "Q8 h; max 150 mg/day", "PO / IM"))]),
  drug("ibuprofen", "Ibuprofen", "Analgesic / anti-inflammatory", [r("Fever/analgesia", "5–10 mg/kg/dose Q6–8 h; max 40 mg/kg/day", kgDose(5, 10, "Q6–8 h; max 40 mg/kg/day", "PO")), r("PDA closure", "10 mg/kg IV followed by 5 mg/kg IV Q24 h ×2 doses", kgDose(10, 10, "Loading then Q24 h ×2", "IV"))]),
  drug("paracetamol", "Paracetamol", "Analgesic / anti-inflammatory", [r("Neonate", "10–15 mg/kg/dose PO/PR Q6–8 h", kgDose(10, 15, "Q6–8 h", "PO / PR")), r("Paediatric", "10–15 mg/kg/dose PO/PR Q4–6 h; max 90 mg/kg/24 h or 4 g/24 h", kgDose(10, 15, "Q4–6 h; max 90 mg/kg/day", "PO / PR"))]),
];

export const PEDIATRIC_DRUG_GROUPS: PediatricDrugGroup[] = ["Antimicrobials", "Respiratory", "Cardiotonic / diuretic", "Neurology / sedation", "Analgesic / anti-inflammatory", "Gastro / allergy", "Supplements", "Other"];
export const getPediatricDrug = (id: string) => PEDIATRIC_DRUGS.find((item) => item.id === id) ?? PEDIATRIC_DRUGS[0];
export function calculatePediatricDose(drug: PediatricDrug, input: PediatricDoseInput, regimenIndex = 0): PediatricDoseResult { return calculateDrug(drug, input, drug.regimens[regimenIndex] ?? drug.regimens[0]); }
