import type { UnitKey } from "@/lib/units";

export type ReferenceProfile = {
  headline: string;
  intro: string;
  monitored: string[];
  targets: string[];
  labs: { label: string; fields: string[] }[];
  drugs: Record<string, string[]>;
  lines: string[];
  care: string[];
  discharge: string[];
};

const NICU: ReferenceProfile = {
  headline: "NICU · Level IIIB",
  intro:
    "Newborn intensive care dataset — AAP (Levels of Neonatal Care, NRP 8th ed., 2022 hyperbilirubinaemia & ROP), NNF India CPG and IAP aligned. Educational decision support only.",
  monitored: [
    "Heart rate (continuous)",
    "Respiratory rate & effort (Silverman / Downes)",
    "SpO₂ pre-ductal (right hand)",
    "SpO₂ post-ductal (foot)",
    "Axillary / skin temperature",
    "Blood pressure, MAP",
    "Capillary refill time & perfusion index",
    "Blood glucose (heel-prick)",
    "Pain score (NIPS / N-PASS / PIPP)",
    "Urine output ml/kg/hr",
    "Stool character & frequency",
    "Gastric residual volume",
    "Abdominal girth",
    "Daily weight, weekly HC & length",
    "Incubator / warmer temperature & humidity",
    "Ventilator settings & alarms",
    "Line dwell day count",
    "Phototherapy hours & irradiance",
    "Sedation / withdrawal score",
  ],
  targets: [
    "Heart rate 100–160/min (sleeping term may dip to 90).",
    "Respiratory rate 30–60/min; sustained > 60 = tachypnoea.",
    "SpO₂ 90–95% preterm on O₂, 92–97% term; pre/post-ductal gap < 3%.",
    "Axillary temperature 97.7–99.5 °F (WHO / NNF normothermia).",
    "Mean BP ≥ gestational age in weeks (first 72 h) with good perfusion.",
    "CRT < 3 s; lactate < 2 mmol/L.",
    "Blood glucose 45–150 mg/dL.",
    "Urine output 1–3 ml/kg/hr after day 1.",
    "Weight gain 15–20 g/kg/day once on full feeds.",
    "Pain: NIPS < 3, PIPP-R ≤ 6, N-PASS ≤ 3 (treat above threshold).",
  ],
  labs: [
    { label: "CBC", fields: ["Hb", "Hct", "TLC", "ANC", "Platelets", "nRBC", "I:T ratio"] },
    { label: "Sepsis screen", fields: ["CRP", "Procalcitonin", "Micro-ESR", "Blood culture"] },
    { label: "ABG", fields: ["pH", "pCO₂", "pO₂", "HCO₃", "BE", "Lactate", "SaO₂"] },
    { label: "Biochemistry", fields: ["Na", "K", "Ca (ionised)", "Mg", "PO₄", "ALP", "Urea", "Creatinine", "Albumin"] },
    { label: "Bilirubin", fields: ["TSB", "Direct", "TcB", "DCT", "Blood group", "Retic"] },
    { label: "Glucose", fields: ["RBS / GRBS", "Lab glucose", "GIR"] },
    { label: "Screening / Imaging", fields: ["Cranial USG", "Echocardiography", "Chest X-ray", "MRI brain", "aEEG / EEG", "TSH newborn screen", "G6PD", "Hearing OAE", "BERA", "ROP screening", "CCHD pulse-ox"] },
  ],
  drugs: {
    Antibiotics: ["Ampicillin", "Penicillin G", "Amoxicillin-Clavulanate", "Cefotaxime", "Ceftazidime", "Piperacillin-tazobactam", "Amikacin", "Gentamicin", "Meropenem", "Vancomycin", "Metronidazole"],
    Antifungal: ["Fluconazole", "Amphotericin B (LAmB)", "Micafungin", "Nystatin oral"],
    Cardiac: ["Dopamine", "Dobutamine", "Adrenaline", "Milrinone", "Hydrocortisone (hypotension)", "PGE1 infusion"],
    Respiratory: ["Caffeine citrate", "Surfactant", "Nebulised adrenaline", "Dexamethasone (DART)", "Furosemide (CLD)"],
    Neuro: ["Phenobarbitone", "Levetiracetam", "Fentanyl", "Morphine", "Sucrose 24%", "Paracetamol (analgesia)"],
    "PDA / Fluids": ["Paracetamol IV (PDA)", "Ibuprofen (PDA)", "Furosemide", "Calcium gluconate", "Sodium bicarbonate", "Insulin infusion"],
    Supplements: ["Vitamin K", "Multivitamin drops", "Vitamin D3 400 IU", "Iron 2–4 mg/kg/day", "Calcium + phosphate", "Probiotics", "Erythropoietin"],
  },
  lines: [
    "Peripheral IV cannula",
    "Umbilical venous catheter (UVC ≤ 7 d)",
    "Umbilical arterial catheter (UAC ≤ 5 d)",
    "PICC line",
    "Endotracheal tube",
    "CPAP prongs / mask",
    "OG / NG tube",
    "Intercostal drain",
    "Peritoneal drain",
    "aEEG leads",
    "Cooling mattress",
  ],
  care: [
    "Kangaroo mother care ≥ 4 h",
    "Mother's own milk expression",
    "Oral care with colostrum",
    "Developmentally supportive positioning",
    "Cluster care & minimal handling",
    "Non-nutritive sucking",
    "Pain assessment every shift",
    "CLABSI bundle & line review",
    "Ventilator bundle (head end up 30°)",
    "Daily weight, weekly HC & length",
    "Family participatory care",
  ],
  discharge: [
    "Temp maintained in open cot × 24 h",
    "Weight gain ≥ 15 g/kg/day × 3 days",
    "Full oral / breast feeds, no tube",
    "No apnoea / brady ≥ 5–7 d off caffeine",
    "Off oxygen / stable home O₂ plan",
    "Newborn screen, hearing, ROP done",
    "Cranial USG / MRI as indicated",
    "Immunisations up to date",
    "Parents trained (feeding, danger signs, CPR)",
    "High-risk follow-up appointment given",
  ],
};

const PICU_BASE = {
  labs: [
    { label: "CBC / coagulation", fields: ["Hb", "Hct", "TLC", "ANC", "Platelets", "PT/INR", "aPTT", "Fibrinogen", "D-dimer"] },
    { label: "Sepsis / inflammation", fields: ["CRP", "Procalcitonin", "Ferritin", "Blood culture ×2", "Lactate"] },
    { label: "ABG / electrolytes", fields: ["pH", "pCO₂", "pO₂", "HCO₃", "BE", "Na", "K", "Cl", "Ca (ionised)", "Mg", "PO₄"] },
    { label: "Renal / hepatic", fields: ["Urea", "Creatinine", "eGFR", "AST", "ALT", "GGT", "Bilirubin", "Ammonia"] },
    { label: "Cardiac", fields: ["Troponin I", "CK-MB", "BNP", "ECG", "Echocardiography"] },
    { label: "Imaging", fields: ["Chest X-ray", "USG abdomen", "CT head", "MRI brain", "EEG / cEEG"] },
    { label: "Special", fields: ["Toxicology screen", "Newborn/metabolic screen", "COVID / RSV / influenza panel", "Blood group & cross-match"] },
  ],
  drugs: {
    Antibiotics: ["Ceftriaxone", "Cefepime", "Piperacillin-tazobactam", "Meropenem", "Vancomycin", "Amikacin", "Linezolid", "Colistin", "Metronidazole", "Clindamycin"],
    Antivirals: ["Oseltamivir", "Acyclovir", "Ganciclovir"],
    Antifungal: ["Fluconazole", "Voriconazole", "Amphotericin B (LAmB)", "Caspofungin"],
    Cardiac: ["Adrenaline", "Noradrenaline", "Dopamine", "Dobutamine", "Milrinone", "Vasopressin", "Nitroglycerine", "Sildenafil", "Digoxin", "Amiodarone", "Adenosine"],
    Respiratory: ["Salbutamol neb", "Ipratropium neb", "Adrenaline neb", "Budesonide neb", "Magnesium sulphate", "Hydrocortisone / methylpred", "Aminophylline"],
    "Sedation / analgesia": ["Fentanyl", "Morphine", "Midazolam", "Dexmedetomidine", "Ketamine", "Paracetamol IV", "Rocuronium", "Vecuronium"],
    Neuro: ["Levetiracetam", "Phenytoin / fosphenytoin", "Phenobarbitone", "Midazolam infusion", "Thiopentone", "Mannitol", "3% saline", "Pyridoxine"],
    "Fluids / metabolic": ["Normal saline bolus", "Ringer lactate", "Albumin 20%", "Dextrose 10%", "Sodium bicarbonate", "Calcium gluconate", "Insulin infusion", "N-acetylcysteine", "Lactulose"],
    Blood: ["PRBC", "FFP", "Platelets", "Cryoprecipitate", "IVIG", "Anti-D"],
  },
  lines: [
    "Central venous catheter (IJ / femoral / subclavian)",
    "Arterial line",
    "Peripheral IV × 2",
    "PICC line",
    "Endotracheal tube",
    "Tracheostomy",
    "NG / OG tube",
    "Foley catheter",
    "Intercostal drain",
    "External ventricular drain",
    "Peritoneal / haemodialysis catheter",
    "ECMO cannulae",
    "ICP monitor",
    "aEEG / cEEG leads",
  ],
  care: [
    "Head end up 30° · ventilator bundle",
    "CLABSI bundle · daily line review",
    "Sedation & pain assessment (COMFORT / FLACC) every shift",
    "Delirium screen (pCAM-ICU / SOS-PD)",
    "Skin / pressure area care q4h",
    "DVT prophylaxis where age-appropriate",
    "Stress-ulcer prophylaxis (indication based)",
    "Family updates every shift",
    "Early mobilisation when stable",
  ],
  discharge: [
    "Off vasoactives ≥ 24 h",
    "Extubated / stable respiratory support",
    "Feeds tolerated · no ileus",
    "Pain / sedation controlled with oral meds",
    "Antibiotics rationalised · sensitivity known",
    "Follow-up outpatient appointment fixed",
    "Parents trained on home care & red-flag signs",
  ],
};

const PICU: ReferenceProfile = {
  headline: "PICU · Paediatric Intensive Care",
  intro:
    "Paediatric intensive care dataset — surviving-sepsis paediatric guidelines, PARDS 2023, PALS 2020, IAP-IJCP protocols. Educational support only.",
  monitored: [
    "Heart rate & rhythm (continuous ECG)",
    "Respiratory rate & work of breathing",
    "SpO₂ · EtCO₂ / TcCO₂",
    "Blood pressure (invasive if unstable)",
    "MAP, CVP if central line",
    "Temperature (core / skin)",
    "Capillary refill · lactate",
    "GCS / AVPU / pupillary size & reaction",
    "Pain (FLACC / Wong-Baker / NRS)",
    "Sedation (COMFORT-B / Richmond)",
    "Delirium screen (pCAM-ICU / SOS-PD)",
    "Fluid balance & hourly urine output",
    "Blood glucose · ketones",
    "Ventilator parameters (Vt, PIP, PEEP, FiO₂, OI)",
    "Airway pressures & compliance",
    "Head circumference (< 2 y)",
    "Weight (daily where feasible)",
  ],
  targets: [
    "Age-appropriate HR & SBP (PALS tables).",
    "SpO₂ ≥ 94% (mild lung disease) · 88–92% permissive in severe PARDS.",
    "PEEP titrated by ARDS-Berlin table · PIP < 28 (unless required).",
    "Permissive hypercapnia pH ≥ 7.20 in PARDS.",
    "MAP > 5th centile for age · maintain end-organ perfusion.",
    "CRT < 2 s · lactate < 2 mmol/L or clearing.",
    "Urine 1–2 ml/kg/hr in children, 2–3 ml/kg/hr in infants.",
    "Glucose 80–180 mg/dL (avoid < 60 or > 200).",
    "GCS ≥ 12 · pupils 2–4 mm equal reactive.",
    "Pain: FLACC ≤ 3 · sedation COMFORT-B 11–22.",
  ],
  labs: PICU_BASE.labs,
  drugs: PICU_BASE.drugs,
  lines: PICU_BASE.lines,
  care: PICU_BASE.care,
  discharge: PICU_BASE.discharge,
};

const STEPDOWN: ReferenceProfile = {
  ...PICU,
  headline: "Step-down PICU / HDU",
  intro:
    "High-dependency step-down — patients weaned from PICU but not ward-ready. Continuous monitoring, single-organ support, close nursing.",
  monitored: [
    "HR & rhythm (continuous)",
    "SpO₂ continuous · RR",
    "NIBP q1–2h",
    "Temperature q4h",
    "Pain (FLACC / Wong-Baker / NRS)",
    "GCS q shift",
    "Hourly urine output",
    "Blood glucose (as indicated)",
    "Oxygen delivery / NIV settings",
    "Daily weight",
  ],
  targets: [
    "SpO₂ ≥ 94% on ≤ 4 L nasal prong O₂ / NIV weaning.",
    "HR & BP within age band · CRT < 2 s.",
    "Urine 1–2 ml/kg/hr.",
    "Pain FLACC ≤ 3.",
    "Feed tolerance ≥ 75% target with no vomiting.",
  ],
};

const POSTNATAL: ReferenceProfile = {
  headline: "Postnatal Ward · Mother & Baby",
  intro:
    "Post-partum mother-and-baby rooming-in unit — WHO postnatal care 2022, ACOG postpartum guidance, NNF/IAP well-baby care.",
  monitored: [
    "Mother: pulse, BP, temperature q4h × 24 h",
    "Mother: pain (0–10 NRS), lochia character",
    "Mother: fundal height & tone",
    "Mother: perineum / caesarean wound",
    "Mother: bladder & bowel function",
    "Mother: DVT screen if risk factors",
    "Baby: temperature, HR, RR",
    "Baby: SpO₂ at 24 h (CCHD screen)",
    "Baby: weight daily",
    "Baby: feeds & voids / stools",
    "Baby: jaundice (TcB / TSB if needed)",
    "Baby: umbilical stump",
    "Baby: pain during procedures (NIPS / PIPP)",
  ],
  targets: [
    "Mother: HR 60–100, BP 110/70–140/90 mmHg, temp 97.7–99.5 °F.",
    "Mother: pain ≤ 3/10 with prescribed analgesia.",
    "Baby: HR 100–160, RR 30–60, SpO₂ ≥ 95% pre & post-ductal (gap < 3%).",
    "Baby: temp 97.7–99.5 °F axillary.",
    "Baby: ≥ 8 breastfeeds / 24 h, ≥ 6 wet nappies by day 3.",
    "Baby: weight loss < 7% term, < 10% preterm by day 5.",
    "Baby: bilirubin under AAP 2022 phototherapy line.",
  ],
  labs: [
    { label: "Mother", fields: ["Hb & Hct", "Blood group & Rh · anti-D status", "Coombs (if Rh-negative)", "RBS / OGTT if GDM", "TSH · thyroid", "Urine routine", "HIV / HBsAg / VDRL (if not tested)"] },
    { label: "Baby", fields: ["Blood group & DCT", "Bilirubin (TcB / TSB)", "RBS (screen at-risk)", "Newborn screen (TSH, G6PD, CAH ± MS/MS)", "Hearing OAE", "CCHD pulse-oximetry"] },
  ],
  drugs: {
    "Mother — analgesia": ["Paracetamol PO/IV", "Ibuprofen (safe with breastfeeding)", "Diclofenac supp", "Tramadol (short course)"],
    "Mother — obstetric": ["Oxytocin infusion", "Methylergometrine", "Misoprostol PR (PPH)", "Tranexamic acid", "Carboprost"],
    "Mother — antibiotics": ["Cefazolin (post-LSCS)", "Amoxicillin-clavulanate", "Metronidazole", "Piperacillin-tazobactam (sepsis)"],
    "Mother — other": ["Iron + folate", "Calcium 500 mg BD", "Vitamin D3", "Anti-D immunoglobulin", "Enoxaparin (VTE prophylaxis)", "Antihypertensives (labetalol / nifedipine)", "Lactation support"],
    "Baby — routine": ["Vitamin K 1 mg IM", "BCG · OPV · Hep-B at birth", "Nystatin oral (thrush)", "Emollient / barrier cream"],
    "Baby — jaundice / feeding": ["Phototherapy", "Formula top-up (if indicated)", "Oral rehydration (paladai)"],
  },
  lines: [
    "Mother: peripheral IV cannula",
    "Mother: Foley catheter (post-LSCS)",
    "Mother: epidural catheter",
    "Mother: intercostal / abdominal drains (rare)",
    "Baby: peripheral IV (if antibiotics)",
    "Baby: NG tube (feeding support)",
    "Baby: phototherapy eye shield",
  ],
  care: [
    "Skin-to-skin contact within 1 hour",
    "Early initiation of breastfeeding",
    "Rooming-in 24 hours",
    "Mother education: latching, positioning, expression",
    "Contraception counselling before discharge",
    "Perineal / caesarean wound care",
    "DVT prophylaxis / early mobilisation",
    "Baby: umbilical cord care · nappy hygiene",
    "Baby: KMC if LBW",
    "Baby: Vitamin K given",
    "Baby: newborn screen, hearing, CCHD done",
    "Danger sign counselling for mother & baby",
  ],
  discharge: [
    "Mother: vitals stable, ambulating, passing urine & stool",
    "Mother: wound / perineum healing · no fever",
    "Mother: contraception & follow-up explained",
    "Mother: iron / calcium prescribed",
    "Baby: feeding well, weight loss < 10%",
    "Baby: jaundice below phototherapy line",
    "Baby: BCG / OPV / Hep-B given",
    "Baby: newborn & hearing screen done",
    "Follow-up in 3–5 days with paediatrician",
  ],
};

const PAEDS: ReferenceProfile = {
  headline: "Paediatric Ward · General",
  intro:
    "General paediatric ward dataset — IAP protocols, WHO IMCI, NICE paediatric CKS. Educational decision support only.",
  monitored: [
    "Vitals q4h (HR, RR, SpO₂, temp, BP)",
    "Pain score (FLACC / Wong-Baker / NRS)",
    "Fluid intake / output",
    "Daily weight",
    "Feeding & appetite",
    "Neuro observation (GCS if head injury / meningitis)",
    "Blood glucose (as indicated)",
    "Rash / hydration / capillary refill",
    "Oxygen requirement",
    "Stool frequency & character",
  ],
  targets: [
    "SpO₂ ≥ 94% room air (≥ 92% chronic lung disease).",
    "HR & RR within age band (WHO IMCI tables).",
    "Temp 97.7–99.5 °F · treat > 101.3 °F.",
    "Blood glucose 70–140 mg/dL.",
    "Urine 1–2 ml/kg/hr.",
    "Pain FLACC / NRS ≤ 3.",
    "Weight gain per age band (WHO growth chart).",
  ],
  labs: [
    { label: "Common", fields: ["CBC", "CRP", "Blood culture", "RBS", "Na", "K", "Urea", "Creatinine", "Urine routine"] },
    { label: "Respiratory", fields: ["Chest X-ray", "RSV / influenza / COVID swab", "Mantoux / IGRA", "Sputum AFB / GeneXpert"] },
    { label: "GI / hepatic", fields: ["LFT", "Stool routine · rota antigen", "USG abdomen"] },
    { label: "Infection", fields: ["Malaria rapid / smear", "Dengue NS1 / IgM / IgG", "Scrub typhus IgM", "Widal / typhoid rapid"] },
    { label: "Special", fields: ["Serum ammonia", "Metabolic screen", "EEG", "MRI brain", "Echocardiography", "Bone marrow"] },
  ],
  drugs: {
    Antibiotics: ["Amoxicillin", "Amoxicillin-Clavulanate", "Azithromycin", "Cefixime", "Ceftriaxone", "Cotrimoxazole", "Cloxacillin", "Metronidazole", "Doxycycline (> 8 y)"],
    "Fever / pain": ["Paracetamol", "Ibuprofen", "Diclofenac", "Sponging protocol"],
    Antiepileptics: ["Levetiracetam", "Sodium valproate", "Phenytoin", "Carbamazepine", "Clobazam", "Diazepam (acute)"],
    Respiratory: ["Salbutamol MDI + spacer", "Budesonide MDI", "Montelukast", "Nebulised adrenaline (croup)"],
    "GI / hydration": ["ORS", "IV fluids (Isolyte-P, Ringer lactate)", "Ondansetron", "Domperidone", "Pantoprazole", "Lactulose"],
    Endocrine: ["Insulin (regular / lispro)", "Thyroxine", "Hydrocortisone (AI)", "Growth hormone"],
    "Anti-inflammatory": ["Prednisolone", "Methylprednisolone", "IVIG", "Aspirin (Kawasaki)"],
    Supplements: ["Iron", "Zinc", "Vitamin A", "Vitamin D3", "Calcium", "Folic acid", "Multivitamin"],
  },
  lines: [
    "Peripheral IV cannula",
    "NG tube (feeding / decompression)",
    "Foley catheter",
    "Chest drain",
    "Peritoneal drain",
    "Oxygen mask / prong",
    "Nebuliser mask",
    "PICC (long IV antibiotics)",
  ],
  care: [
    "Age-appropriate play & distraction during procedures",
    "Isolation as per infection (droplet / contact / airborne)",
    "Hand hygiene 5 moments",
    "Nutrition assessment (WHO chart)",
    "Immunisation review & catch-up",
    "Discharge teaching in local language",
    "Follow-up appointment fixed",
    "Safeguarding screen where indicated",
  ],
  discharge: [
    "Afebrile ≥ 24 h · no worsening",
    "Feeding adequately · hydrated",
    "Off oxygen / stable",
    "Oral medications tolerated",
    "Danger signs explained",
    "Immunisation status updated",
    "Follow-up appointment given",
  ],
};

export const UNIT_REFERENCE: Record<UnitKey, ReferenceProfile> = {
  nicu: NICU,
  picu: PICU,
  stepdown: STEPDOWN,
  postnatal: POSTNATAL,
  paeds: PAEDS,
};
