import type { UnitKey } from "./units";
import { PROBLEM_CATALOG as NICU_CATALOG, type SystemKey } from "./catalog";

type Sys = SystemKey | "PICU General" | "Sub-specialty" | "Maternal / Postnatal" | "Newborn (well)" | "Ward general";

const PICU_SYSTEMS: Sys[] = [
  "Respiratory",
  "Cardiovascular",
  "Neurology",
  "Gastro / Nutrition",
  "Metabolic / Endocrine",
  "Infection",
  "Haematology / Bilirubin",
  "Renal / GU",
  "Thermoregulation",
  "Eye / ENT",
  "Surgical",
  "Genetic / Syndromic",
  "Birth injury / Skin",
  "Growth / Prematurity",
  "PICU General",
  "Sub-specialty",
];

/** Full PICU diagnosis list — admission to discharge. */
export const PICU_CATALOG: Record<string, string[]> = {
  Respiratory: [
    "Acute severe asthma / status asthmaticus",
    "Bronchiolitis – RSV",
    "Pneumonia – community acquired",
    "Pneumonia – ventilator associated",
    "ARDS / PARDS",
    "Acute laryngotracheobronchitis (croup)",
    "Bacterial tracheitis",
    "Epiglottitis",
    "Retropharyngeal / peritonsillar abscess",
    "Foreign body airway – post removal",
    "Upper airway obstruction – post extubation stridor",
    "Pneumothorax / air leak",
    "Pleural effusion / empyema – ICD in situ",
    "Lung collapse / atelectasis",
    "Pulmonary haemorrhage",
    "Pulmonary tuberculosis – on treatment",
    "Chronic lung disease / tracheostomy dependent",
    "Obstructive sleep apnoea – post adenotonsillectomy",
    "Neuromuscular respiratory failure (GBS / myasthenia)",
    "Spinal muscular atrophy – respiratory support",
    "Drowning / near drowning – aspiration",
    "Smoke inhalation injury",
    "Post operative ventilation – airway surgery",
    "Difficult airway / failed extubation",
    "Non-invasive ventilation (CPAP / BiPAP)",
    "High flow nasal oxygen therapy",
  ],
  Cardiovascular: [
    "Shock – compensated",
    "Septic shock",
    "Cardiogenic shock / myocarditis",
    "Dengue shock syndrome",
    "Hypovolaemic shock – gastroenteritis",
    "Refractory shock – on multiple inotropes",
    "Congestive cardiac failure",
    "Acute rheumatic fever / carditis",
    "Rheumatic heart disease – severe MS / MR",
    "Infective endocarditis",
    "Cyanotic congenital heart disease – pre op",
    "Cyanotic congenital heart disease – post op",
    "Acyanotic CHD – VSD / ASD / PDA",
    "Post cardiac surgery – low cardiac output syndrome",
    "Post cardiac catheterisation – observation",
    "Arrhythmia – SVT",
    "Arrhythmia – complete heart block / pacemaker",
    "Arrhythmia – ventricular tachycardia",
    "Long QT syndrome",
    "Hypertensive emergency",
    "Pulmonary hypertension crisis",
    "Pericardial effusion / tamponade",
    "Kawasaki disease – coronary involvement",
    "Myocardial infarction – Kawasaki / anomalous coronaries",
    "ECMO / VAD support",
  ],
  Neurology: [
    "Status epilepticus",
    "Refractory epilepsy – on midazolam / phenobarbitone infusion",
    "Bacterial meningitis",
    "Tubercular meningitis",
    "Viral encephalitis – HSV",
    "Acute disseminated encephalomyelitis (ADEM)",
    "Guillain–Barré syndrome – on ventilation",
    "Transverse myelitis",
    "Myasthenic crisis",
    "Neurotrauma – severe TBI",
    "Raised ICP – ICP monitor in situ",
    "Intracranial haemorrhage",
    "Stroke – arterial ischaemic",
    "Cerebral venous sinus thrombosis",
    "Brain abscess",
    "Post neurosurgery – craniotomy care",
    "Ventriculoperitoneal shunt – blockage / infection",
    "Neurodegenerative disease – end stage",
    "Brain death – evaluation in progress",
    "Neuromuscular blockade – ongoing",
    "Targeted temperature management",
    "Spinal cord injury",
    "Encephalopathy – metabolic / toxic",
  ],
  "Gastro / Nutrition": [
    "Acute liver failure",
    "Hepatic encephalopathy",
    "Fulminant hepatic failure – transplant workup",
    "GI bleed – upper / lower",
    "Portal hypertension – variceal bleed",
    "Acute pancreatitis",
    "Bowel obstruction – post op",
    "Intussusception – post reduction",
    "Peritonitis – perforation",
    "Inflammatory bowel disease – flare",
    "Malnutrition – severe acute (SAM) with complications",
    "Refeeding syndrome",
    "Short bowel syndrome on TPN",
    "Cholestasis / TPN liver disease",
    "Abdominal compartment syndrome",
    "Post laparotomy – open abdomen",
    "Stoma – high output",
    "Post operative ileus",
    "Caustic ingestion – oesophagitis",
    "Corrosive poisoning – GI injury",
  ],
  "Metabolic / Endocrine": [
    "Diabetic ketoacidosis – on insulin infusion",
    "Diabetic ketoacidosis – resolving",
    "Hypoglycaemia – recurrent",
    "Adrenal crisis – on hydrocortisone",
    "Congenital adrenal hyperplasia – salt wasting",
    "Diabetes insipidus – central",
    "SIADH",
    "Thyroid storm",
    "Myxoedema coma",
    "Hyperosmolar hyperglycaemic state",
    "Inborn error of metabolism – decompensation",
    "Hyperammonaemia – on scavenger therapy",
    "Mitochondrial crisis",
    "Electrolyte crisis – severe hyponatraemia",
    "Tumour lysis syndrome",
    "Rhabdomyolysis – AKI",
  ],
  Infection: [
    "Sepsis – organ dysfunction",
    "Septic shock – on vasopressors",
    "Nosocomial / ventilator associated pneumonia",
    "CLABSI – central line infection",
    "CAUTI – catheter associated UTI",
    "Meningococcaemia",
    "Typhoid fever – complicated",
    "Malaria – severe / cerebral",
    "Dengue – severe plasma leakage",
    "Chikungunya – severe",
    "Leptospirosis – severe",
    "Scrub typhus",
    "Visceral leishmaniasis",
    "HIV – PCP / opportunistic infection",
    "Candidaemia – on antifungal",
    "Aspergillosis – invasive",
    "Mucormycosis – post COVID",
    "COVID-19 – MIS-C",
    "COVID-19 – severe pneumonia",
    "Multidrug resistant organism – isolation",
    "Necrotising fasciitis",
    "Clostridium difficile colitis",
    "Tetanus – neonatal / older child",
    "Rabies – post exposure",
  ],
  "Haematology / Bilirubin": [
    "Severe anaemia – transfusion dependent",
    "Haemolytic uraemic syndrome",
    "Immune thrombocytopenia – severe",
    "Thrombotic thrombocytopenic purpura",
    "Disseminated intravascular coagulation",
    "Haemophilia – bleeding episode",
    "Von Willebrand disease – bleeding",
    "Acute lymphoblastic leukaemia – induction",
    "Acute myeloid leukaemia – chemo",
    "Febrile neutropenia",
    "Tumour lysis – on hydration",
    "Mediastinal mass – airway compromise",
    "Sickle cell crisis – vaso-occlusive",
    "Sickle cell – acute chest syndrome",
    "Thalassaemia – transfusion reaction",
    "Post bone marrow transplant – engraftment",
    "Graft versus host disease",
    "Massive transfusion protocol – activated",
    "Exchange transfusion – in progress",
  ],
  "Renal / GU": [
    "AKI – pre renal",
    "AKI – renal / ATN",
    "AKI – on dialysis / CRRT",
    "Haemolytic uraemic syndrome – dialysis",
    "Nephrotic syndrome – complicated",
    "Nephritic syndrome – RPGN",
    "Posterior urethral valves – urosepsis",
    "Obstructive uropathy – post nephrostomy",
    "Urolithiasis – obstructive",
    "Severe electrolyte derangement",
    "Rhabdomyolysis – renal failure",
    "Post renal transplant – rejection",
  ],
  Thermoregulation: [
    "Hypothermia – therapeutic / post arrest",
    "Hyperpyrexia – heat stroke",
    "Malignant hyperthermia – post anaesthesia",
    "Neuroleptic malignant syndrome",
    "Serotonin syndrome",
  ],
  "Eye / ENT": [
    "Corneal ulcer – exposure keratopathy",
    "Retinal haemorrhage – NAI workup",
    "Acute mastoiditis",
    "Post tonsillectomy – secondary haemorrhage",
    "Post airway surgery – stoma care",
    "Foreign body ear / nose – post removal",
  ],
  Surgical: [
    "Post operative – day 1 major surgery",
    "Post operative – on ventilation",
    "Trauma – polytrauma",
    "Head injury – moderate / severe",
    "Chest trauma – haemothorax",
    "Abdominal trauma – solid organ injury",
    "Burns – >20% TBSA",
    "Burns – inhalational injury",
    "Electrical / chemical burn",
    "Crush injury – compartment syndrome",
    "Fasciotomy in situ",
    "Post cardiac surgery – sternal closure",
    "Tracheostomy – fresh",
    "Chest drain in situ",
    "Peritoneal drain in situ",
    "Colostomy / ileostomy in situ",
    "Awaiting surgical intervention",
    "Re-exploration planned",
  ],
  "Genetic / Syndromic": [
    "Down syndrome – cardiac lesion",
    "Trisomy 18 – palliative care",
    "Muscular dystrophy – respiratory decline",
    "Spinal muscular atrophy – on nusinersen",
    "Mitochondrial disorder",
    "Mucopolysaccharidosis – airway",
    "Osteogenesis imperfecta – fracture",
    "Dysmorphic syndrome – undiagnosed",
  ],
  "Birth injury / Skin": [
    "Stevens–Johnson syndrome / TEN",
    "Toxic epidermal necrolysis – on care",
    "Erythroderma",
    "Severe atopic dermatitis – infected",
    "Kawasaki – desquamating rash",
    "Extensive haemangioma – PHACE",
    "Arteriovenous malformation",
    "Pressure injury – device related",
    "Extravasation injury – Slough",
  ],
  "Growth / Prematurity": [
    "Failure to thrive – severe",
    "Malnutrition – SAM with medical complication",
    "Refeeding syndrome – risk",
    "Chronic undernutrition on NG feeds",
  ],
  "PICU General": [
    "Post cardiopulmonary arrest – post ROSC care",
    "Near drowning – multi organ support",
    "Poisoning – organophosphate",
    "Poisoning – hydrocarbon",
    "Poisoning – snake bite / envenomation",
    "Poisoning – scorpion sting",
    "Poisoning – unknown ingestant",
    "Sedation / analgesia – on infusion",
    "Mechanical ventilation – invasive",
    "Tracheostomy – chronic ventilation",
    "High dependency – on NIV",
    "Post operative transfer from OT",
    "Interfacility transfer – accepted",
    "End of life care – palliative",
    "Organ donation – pathway",
    "Family counselling in progress",
  ],
  "Sub-specialty": [
    "CCU admission – neuro / trauma overflow",
    "CCU admission – post cardiac arrest",
    "CVICU – post ASD / VSD closure",
    "CVICU – post TOF repair",
    "CVICU – post AV canal repair",
    "CVICU – post arch repair / coarctation",
    "CVICU – post Fontan / Glenn",
    "CVICU – ECMO decannulation",
    "CVICU – pleural / pericardial drain",
    "CVICU – pacing wires in situ",
    "CVICU – inotrope weaning",
    "LICU – acute liver failure grade I–II",
    "LICU – acute liver failure grade III–IV",
    "LICU – hepatic encephalopathy – on lactulose",
    "LICU – post liver transplant",
    "LICU – fulminant hepatic failure – NAC infusion",
    "LICU – variceal bleed – post banding",
    "LICU – hepatorenal syndrome",
    "LICU – coagulopathy – on FFP / cryo",
    "LICU – liver transplant workup – listed",
  ],
};

/** Postnatal ward — mother & baby, all stable cases. */
export const POSTNATAL_CATALOG: Record<string, string[]> = {
  "Maternal / Postnatal": [
    "Normal vaginal delivery – postnatal day 1",
    "Normal vaginal delivery – postnatal day 2–3",
    "Instrumental delivery – perineal tear",
    "Instrumental delivery – episiotomy care",
    "Lower segment caesarean – post op day 1",
    "Lower segment caesarean – post op day 2–3",
    "Emergency caesarean – post op",
    "Caesarean – spinal / epidural analgesia ongoing",
    "Post op – catheter in situ",
    "Post op – IV antibiotics ongoing",
    "Post op – analgesia on demand",
    "Post op – ambulation commenced",
    "Gynaecological post op – abdominal hysterectomy",
    "Gynaecological post op – vaginal hysterectomy",
    "Gynaecological post op – myomectomy",
    "Gynaecological post op – ovarian cystectomy",
    "Gynaecological post op – laparoscopy",
    "Gynaecological post op – prolapse repair",
    "Gynaecological post op – tubal ligation",
    "Gynaecological post op – hysteroscopy",
    "Labour room – in active labour",
    "Labour room – second stage",
    "Labour room – preterm labour on tocolysis",
    "Labour room – labour induced",
    "Labour room – augmentation with oxytocin",
    "Labour room – meconium stained liquor",
    "Labour room – fetal distress – for LSCS",
    "Labour room – post delivery observation",
    "Labour room – retained placenta managed",
    "Labour room – peripartum hysterectomy",
    "Pre-eclampsia – post delivery monitoring",
    "Eclampsia – post magnesium sulphate",
    "Gestational diabetes – post delivery glucose",
    "Anaemia in pregnancy – post delivery",
    "Thrombocytopenia in pregnancy – post delivery",
    "Hypothyroidism – on thyroxine",
    "Rh negative mother – anti-D given",
    "Blood group incompatibility – baby on watch",
    "Post partum haemorrhage – managed",
    "PPH – Bakri balloon in situ",
    "PPH – blood transfusion given",
    "Retained products – for evacuation",
    "Puerperal pyrexia – on antibiotics",
    "Urinary tract infection – postnatal",
    "Wound infection – caesarean site",
    "Wound gape – for resuturing",
    "Mastitis – on antibiotics",
    "Breast engorgement – managed",
    "Cracked nipples – lactation support",
    "Post partum haemorrhoid – symptomatic",
    "Post partum depression – for counselling",
    "Post partum psychosis – psychiatric referral",
    "Venous thromboembolism – on LMWH",
    "Deep vein thrombosis – postnatal",
    "Epilepsy – on anti epileptics",
    "Cardiac disease in pregnancy – post delivery",
    "Post spinal headache",
    "Bladder retention – re-catheterised",
    "Symphysiolysis / pelvic pain",
    "Fourth degree tear – repair",
    "Discharge planned – mother and baby together",
  ],
  "Newborn (well)": [
    "Well newborn – rooming in with mother",
    "Well newborn – on demand breastfeeding",
    "Well newborn – direct breastfeeding established",
    "Well newborn – expressed breast milk feeds",
    "Well newborn – paladai / katori spoon feeds",
    "Well newborn – phototherapy for jaundice",
    "Well newborn – jaundice under observation",
    "Well newborn – transcutaneous bilirubin monitoring",
    "Well newborn – serum bilirubin sent",
    "Well newborn – on observation for sepsis",
    "Well newborn – antibiotics started",
    "Well newborn – antibiotics stopped",
    "Well newborn – hypoglycaemia on watch",
    "Well newborn – glucose monitoring ongoing",
    "Well newborn – preterm 34–36+6 wk",
    "Well newborn – low birth weight 2000–2499 g",
    "Well newborn – small for gestational age",
    "Well newborn – large for gestational age",
    "Well newborn – infant of diabetic mother",
    "Well newborn – infant of hypertensive mother",
    "Well newborn – transient tachypnoea",
    "Well newborn – mild respiratory distress",
    "Well newborn – nasal oxygen",
    "Well newborn – apnoea of prematurity",
    "Well newborn – temperature instability",
    "Well newborn – under warmer",
    "Well newborn – cot with mother",
    "Well newborn – Vitamin K given",
    "Well newborn – BCG / OPV / HepB given",
    "Well newborn – newborn screening done",
    "Well newborn – hearing screen done",
    "Well newborn – CCHD pulse oximetry screen done",
    "Well newborn – G6PD deficiency detected",
    "Well newborn – congenital hypothyroidism – on treatment",
    "Well newborn – umbilical stump care",
    "Well newborn – nappy rash",
    "Well newborn – cephalhaematoma",
    "Well newborn – caput succedaneum",
    "Well newborn – facial asymmetry / forceps mark",
    "Well newborn – clavicle fracture – managed",
    "Well newborn – brachial plexus injury – physio",
    "Well newborn – subgaleal haemorrhage – observed",
    "Well newborn – oral thrush",
    "Well newborn – nappy dermatitis",
    "Well newborn – breast milk jaundice",
    "Well newborn – weight loss <10% – monitored",
    "Well newborn – poor feeding support given",
    "Well newborn – lactation counselling done",
    "Well newborn – kangaroo mother care",
    "Well newborn – circumcision post op",
    "Well newborn – tongue tie – for release",
    "Well newborn – cleft lip / palate – feeding support",
    "Well newborn – polydactyly – for surgical opinion",
    "Well newborn – congenital dermal melanocytosis",
    "Well newborn – neonatal urticaria",
    "Well newborn – feeding intolerance",
    "Well newborn – vomiting – under evaluation",
    "Well newborn – constipation – managed",
    "Well newborn – discharge counselling done",
    "Well newborn – danger signs explained",
    "Well newborn – immunisation schedule explained",
    "Well newborn – follow up appointment given",
    "Well newborn – mother trained for bathing",
    "Well newborn – cord care training done",
  ],
};

/** Paediatric ward — general ward cases. */
export const PAEDS_CATALOG: Record<string, string[]> = {
  "Ward general": [
    "Acute gastroenteritis – on ORS",
    "Acute gastroenteritis – on IV fluids",
    "Acute gastroenteritis – dehydration corrected",
    "Persistent vomiting – on antiemetics",
    "Dysentery – on antibiotics",
    "Typhoid fever – on antibiotics",
    "Urinary tract infection – on antibiotics",
    "Pneumonia – on oral antibiotics",
    "Pneumonia – on IV antibiotics",
    "Bronchiolitis – on nasal oxygen",
    "Asthma – acute mild / moderate",
    "Asthma – on nebulisation q4h",
    "Asthma – on controller therapy",
    "Croup – on dexamethasone",
    "Otitis media – on antibiotics",
    "Tonsillitis / pharyngitis – on antibiotics",
    "Dengue fever – without warning signs",
    "Dengue – with warning signs",
    "Dengue – on IV fluids",
    "Chikungunya – supportive",
    "Malaria – on antimalarials",
    "Enteric fever – recovery phase",
    "Leptospirosis – on antibiotics",
    "Scrub typhus – on doxycycline",
    "Chickenpox – isolated",
    "Measles – isolated",
    "Mumps – supportive",
    "Hand foot mouth disease – supportive",
    "Herpes zoster – on acyclovir",
    "Viral exanthem – under evaluation",
    "Kawasaki disease – on IVIG",
    "Kawasaki – on aspirin",
    "Acute rheumatic fever – on penicillin",
    "Rheumatic heart disease – on prophylaxis",
    "Nephrotic syndrome – on steroids",
    "Nephrotic syndrome – relapse",
    "Nephritic syndrome – on treatment",
    "Acute post streptococcal GN",
    "UTI with reflux – on prophylaxis",
    "Iron deficiency anaemia – on iron",
    "Megaloblastic anaemia – on B12",
    "Thalassaemia – for transfusion",
    "Sickle cell trait – counselling",
    "ITP – on observation",
    "Haemophilia – factor given",
    "Leukaemia – maintenance chemo",
    "Lymphoma – on chemotherapy",
    "Solid tumour – on chemo",
    "Febrile neutropenia – on antibiotics",
    "Seizure disorder – on antiepileptics",
    "Seizure disorder – well controlled",
    "Febrile seizure – simple",
    "Febrile seizure – complex",
    "Cerebral palsy – on physiotherapy",
    "Global developmental delay – for therapy",
    "Autism spectrum – for evaluation",
    "ADHD – on behaviour therapy",
    "Epileptic encephalopathy – on polytherapy",
    "Guillain–Barré – recovering",
    "Myasthenia – on pyridostigmine",
    "Hypothyroidism – on thyroxine",
    "Type 1 diabetes – on insulin",
    "Type 1 diabetes – newly diagnosed",
    "Precocious puberty – for evaluation",
    "Short stature – for evaluation",
    "Obesity – lifestyle counselling",
    "Vitamin D deficiency – on supplementation",
    "Rickets – on calcium / vitamin D",
    "SAM – on F75 / F100",
    "SAM – on supplementation",
    "Moderate acute malnutrition",
    "Celiac disease – on gluten free diet",
    "Lactose intolerance – on lactose free milk",
    "Chronic constipation – on laxatives",
    "Recurrent abdominal pain – under evaluation",
    "Peptic ulcer disease – on PPI",
    "Helicobacter – on triple therapy",
    "Acute hepatitis – supportive",
    "Chronic liver disease – on treatment",
    "Wilson disease – on chelation",
    "Biliary atresia – post Kasai",
    "Post op – appendicectomy",
    "Post op – herniotomy",
    "Post op – orchidopexy",
    "Post op – circumcision",
    "Post op – laparotomy",
    "Post op – wound care",
    "Foreign body ingestion – observed",
    "Foreign body – button battery – removed",
    "Corrosive poisoning – on treatment",
    "Organophosphate poisoning – recovered",
    "Snake bite – on observation",
    "Scorpion sting – recovered",
    "Drowning – recovered",
    "Road traffic accident – stable",
    "Fracture – on traction",
    "Fracture – plaster in situ",
    "Head injury – mild – observed",
    "Soft tissue injury – managed",
    "Cellulitis – on antibiotics",
    "Abscess – post drainage",
    "Necrotising fasciitis – healing",
    "Burns – minor – on dressing",
    "Animal bite – on vaccination",
    "Tuberculosis – on ATT",
    "Tubercular lymphadenitis – on ATT",
    "Tubercular meningitis – on ATT",
    "Neurocysticercosis – on albendazole",
    "Hydatid cyst – post surgery",
    "Echinococcal – on albendazole",
    "Helminthic infestation – on albendazole",
    "Amoebic liver abscess – on metronidazole",
    "Pyogenic abscess – on antibiotics",
    "Juvenile idiopathic arthritis – on DMARD",
    "Systemic lupus – on steroids",
    "Vasculitis – on immunosuppression",
    "Henoch–Schonlein purpura – supportive",
    "Down syndrome – under follow up",
    "Genetic syndrome – for evaluation",
    "Thalassaemia – on chelation",
    "Aplastic anaemia – for transplant",
    "Discharge planned",
    "Discharge counselling done",
    "Follow up appointment given",
    "Immunisation due / given",
  ],
};

export const UNIT_CATALOGS: Record<UnitKey, Record<string, string[]>> = {
  nicu: NICU_CATALOG,
  picu: PICU_CATALOG,
  stepdown: PICU_CATALOG,
  postnatal: POSTNATAL_CATALOG,
  paeds: PAEDS_CATALOG,
};

export { NICU_CATALOG };

export function systemsForUnit(unit: UnitKey): string[] {
  return Object.keys(UNIT_CATALOGS[unit] ?? {});
}

export function systemOfDiagnosis(unit: UnitKey, label: string): string {
  const catalog = UNIT_CATALOGS[unit] ?? {};
  for (const [system, labels] of Object.entries(catalog)) {
    if (labels.includes(label)) return system;
  }
  return Object.keys(catalog)[0] ?? "General";
}
